// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contentoperationsvr.proto

package contentoperationsvr

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ContentStatus int32

const (
	ContentStatus_ORIGIN  ContentStatus = 0
	ContentStatus_ONLINE  ContentStatus = 1
	ContentStatus_OFFLINE ContentStatus = 2
	ContentStatus_DELETE  ContentStatus = 3
	ContentStatus_TOP     ContentStatus = 4
)

var ContentStatus_name = map[int32]string{
	0: "ORIGIN",
	1: "ONLINE",
	2: "OFFLINE",
	3: "DELETE",
	4: "TOP",
}

var ContentStatus_value = map[string]int32{
	"ORIGIN":  0,
	"ONLINE":  1,
	"OFFLINE": 2,
	"DELETE":  3,
	"TOP":     4,
}

func (x ContentStatus) String() string {
	return proto.EnumName(ContentStatus_name, int32(x))
}

func (ContentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{0}
}

// UserID 用户ID
type UserID struct {
	UnionId              string   `protobuf:"bytes,1,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`
	Openid               string   `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{0}
}
func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func (m *UserID) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *UserID) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type User struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HeadUrl              string   `protobuf:"bytes,2,opt,name=head_url,json=headUrl,proto3" json:"head_url,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{1}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *User) GetHeadUrl() string {
	if m != nil {
		return m.HeadUrl
	}
	return ""
}

func (m *User) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

// *******************************用户信息接口******************************
type LoginReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{2}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LoginRsp struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{3}
}
func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

type UserInfo struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ArticleNum           int32    `protobuf:"varint,2,opt,name=article_num,json=articleNum,proto3" json:"article_num,omitempty"`
	WoaNum               int32    `protobuf:"varint,3,opt,name=woa_num,json=woaNum,proto3" json:"woa_num,omitempty"`
	ReadNum              int32    `protobuf:"varint,4,opt,name=read_num,json=readNum,proto3" json:"read_num,omitempty"`
	FansNum              int32    `protobuf:"varint,5,opt,name=fans_num,json=fansNum,proto3" json:"fans_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{4}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserInfo) GetArticleNum() int32 {
	if m != nil {
		return m.ArticleNum
	}
	return 0
}

func (m *UserInfo) GetWoaNum() int32 {
	if m != nil {
		return m.WoaNum
	}
	return 0
}

func (m *UserInfo) GetReadNum() int32 {
	if m != nil {
		return m.ReadNum
	}
	return 0
}

func (m *UserInfo) GetFansNum() int32 {
	if m != nil {
		return m.FansNum
	}
	return 0
}

type GetUserInfoReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{5}
}
func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

func (m *GetUserInfoReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

type GetUserInfoRsp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserInfoRsp) Reset()         { *m = GetUserInfoRsp{} }
func (m *GetUserInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRsp) ProtoMessage()    {}
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{6}
}
func (m *GetUserInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRsp.Unmarshal(m, b)
}
func (m *GetUserInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRsp.Merge(m, src)
}
func (m *GetUserInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRsp.Size(m)
}
func (m *GetUserInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRsp proto.InternalMessageInfo

func (m *GetUserInfoRsp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

// *******************************文章接口******************************
type Article struct {
	Author               *User         `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	ArticleId            string        `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title                string        `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Desc                 string        `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Url                  string        `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Answer               string        `protobuf:"bytes,6,opt,name=answer,proto3" json:"answer,omitempty"`
	PublishTs            int64         `protobuf:"varint,7,opt,name=publish_ts,json=publishTs,proto3" json:"publish_ts,omitempty"`
	Status               ContentStatus `protobuf:"varint,8,opt,name=status,proto3,enum=contentoperationsvr.ContentStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{7}
}
func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetAuthor() *User {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Article) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Article) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Article) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *Article) GetPublishTs() int64 {
	if m != nil {
		return m.PublishTs
	}
	return 0
}

func (m *Article) GetStatus() ContentStatus {
	if m != nil {
		return m.Status
	}
	return ContentStatus_ORIGIN
}

type PublishArticleReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Article              *Article `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishArticleReq) Reset()         { *m = PublishArticleReq{} }
func (m *PublishArticleReq) String() string { return proto.CompactTextString(m) }
func (*PublishArticleReq) ProtoMessage()    {}
func (*PublishArticleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{8}
}
func (m *PublishArticleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishArticleReq.Unmarshal(m, b)
}
func (m *PublishArticleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishArticleReq.Marshal(b, m, deterministic)
}
func (m *PublishArticleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishArticleReq.Merge(m, src)
}
func (m *PublishArticleReq) XXX_Size() int {
	return xxx_messageInfo_PublishArticleReq.Size(m)
}
func (m *PublishArticleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishArticleReq.DiscardUnknown(m)
}

var xxx_messageInfo_PublishArticleReq proto.InternalMessageInfo

func (m *PublishArticleReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *PublishArticleReq) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

type PublishArticleRsp struct {
	ArticleId            string   `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishArticleRsp) Reset()         { *m = PublishArticleRsp{} }
func (m *PublishArticleRsp) String() string { return proto.CompactTextString(m) }
func (*PublishArticleRsp) ProtoMessage()    {}
func (*PublishArticleRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{9}
}
func (m *PublishArticleRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishArticleRsp.Unmarshal(m, b)
}
func (m *PublishArticleRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishArticleRsp.Marshal(b, m, deterministic)
}
func (m *PublishArticleRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishArticleRsp.Merge(m, src)
}
func (m *PublishArticleRsp) XXX_Size() int {
	return xxx_messageInfo_PublishArticleRsp.Size(m)
}
func (m *PublishArticleRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishArticleRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PublishArticleRsp proto.InternalMessageInfo

func (m *PublishArticleRsp) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

type GetMyArticlesReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyArticlesReq) Reset()         { *m = GetMyArticlesReq{} }
func (m *GetMyArticlesReq) String() string { return proto.CompactTextString(m) }
func (*GetMyArticlesReq) ProtoMessage()    {}
func (*GetMyArticlesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{10}
}
func (m *GetMyArticlesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyArticlesReq.Unmarshal(m, b)
}
func (m *GetMyArticlesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyArticlesReq.Marshal(b, m, deterministic)
}
func (m *GetMyArticlesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyArticlesReq.Merge(m, src)
}
func (m *GetMyArticlesReq) XXX_Size() int {
	return xxx_messageInfo_GetMyArticlesReq.Size(m)
}
func (m *GetMyArticlesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyArticlesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyArticlesReq proto.InternalMessageInfo

func (m *GetMyArticlesReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

type GetMyArticlesRsp struct {
	Articles             []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMyArticlesRsp) Reset()         { *m = GetMyArticlesRsp{} }
func (m *GetMyArticlesRsp) String() string { return proto.CompactTextString(m) }
func (*GetMyArticlesRsp) ProtoMessage()    {}
func (*GetMyArticlesRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{11}
}
func (m *GetMyArticlesRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyArticlesRsp.Unmarshal(m, b)
}
func (m *GetMyArticlesRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyArticlesRsp.Marshal(b, m, deterministic)
}
func (m *GetMyArticlesRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyArticlesRsp.Merge(m, src)
}
func (m *GetMyArticlesRsp) XXX_Size() int {
	return xxx_messageInfo_GetMyArticlesRsp.Size(m)
}
func (m *GetMyArticlesRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyArticlesRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyArticlesRsp proto.InternalMessageInfo

func (m *GetMyArticlesRsp) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

type GetArticleReadersReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArticleId            string   `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleReadersReq) Reset()         { *m = GetArticleReadersReq{} }
func (m *GetArticleReadersReq) String() string { return proto.CompactTextString(m) }
func (*GetArticleReadersReq) ProtoMessage()    {}
func (*GetArticleReadersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{12}
}
func (m *GetArticleReadersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleReadersReq.Unmarshal(m, b)
}
func (m *GetArticleReadersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleReadersReq.Marshal(b, m, deterministic)
}
func (m *GetArticleReadersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleReadersReq.Merge(m, src)
}
func (m *GetArticleReadersReq) XXX_Size() int {
	return xxx_messageInfo_GetArticleReadersReq.Size(m)
}
func (m *GetArticleReadersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleReadersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleReadersReq proto.InternalMessageInfo

func (m *GetArticleReadersReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *GetArticleReadersReq) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

type GetArticleReadersRsp struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleReadersRsp) Reset()         { *m = GetArticleReadersRsp{} }
func (m *GetArticleReadersRsp) String() string { return proto.CompactTextString(m) }
func (*GetArticleReadersRsp) ProtoMessage()    {}
func (*GetArticleReadersRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{13}
}
func (m *GetArticleReadersRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleReadersRsp.Unmarshal(m, b)
}
func (m *GetArticleReadersRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleReadersRsp.Marshal(b, m, deterministic)
}
func (m *GetArticleReadersRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleReadersRsp.Merge(m, src)
}
func (m *GetArticleReadersRsp) XXX_Size() int {
	return xxx_messageInfo_GetArticleReadersRsp.Size(m)
}
func (m *GetArticleReadersRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleReadersRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleReadersRsp proto.InternalMessageInfo

func (m *GetArticleReadersRsp) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type SetArticleStatusReq struct {
	UserId               *UserID       `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArticleId            string        `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Status               ContentStatus `protobuf:"varint,3,opt,name=status,proto3,enum=contentoperationsvr.ContentStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetArticleStatusReq) Reset()         { *m = SetArticleStatusReq{} }
func (m *SetArticleStatusReq) String() string { return proto.CompactTextString(m) }
func (*SetArticleStatusReq) ProtoMessage()    {}
func (*SetArticleStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{14}
}
func (m *SetArticleStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetArticleStatusReq.Unmarshal(m, b)
}
func (m *SetArticleStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetArticleStatusReq.Marshal(b, m, deterministic)
}
func (m *SetArticleStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetArticleStatusReq.Merge(m, src)
}
func (m *SetArticleStatusReq) XXX_Size() int {
	return xxx_messageInfo_SetArticleStatusReq.Size(m)
}
func (m *SetArticleStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetArticleStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetArticleStatusReq proto.InternalMessageInfo

func (m *SetArticleStatusReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *SetArticleStatusReq) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

func (m *SetArticleStatusReq) GetStatus() ContentStatus {
	if m != nil {
		return m.Status
	}
	return ContentStatus_ORIGIN
}

type SetArticleStatusRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetArticleStatusRsp) Reset()         { *m = SetArticleStatusRsp{} }
func (m *SetArticleStatusRsp) String() string { return proto.CompactTextString(m) }
func (*SetArticleStatusRsp) ProtoMessage()    {}
func (*SetArticleStatusRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{15}
}
func (m *SetArticleStatusRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetArticleStatusRsp.Unmarshal(m, b)
}
func (m *SetArticleStatusRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetArticleStatusRsp.Marshal(b, m, deterministic)
}
func (m *SetArticleStatusRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetArticleStatusRsp.Merge(m, src)
}
func (m *SetArticleStatusRsp) XXX_Size() int {
	return xxx_messageInfo_SetArticleStatusRsp.Size(m)
}
func (m *SetArticleStatusRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetArticleStatusRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SetArticleStatusRsp proto.InternalMessageInfo

type ReadArticleReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArticleId            string   `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadArticleReq) Reset()         { *m = ReadArticleReq{} }
func (m *ReadArticleReq) String() string { return proto.CompactTextString(m) }
func (*ReadArticleReq) ProtoMessage()    {}
func (*ReadArticleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{16}
}
func (m *ReadArticleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadArticleReq.Unmarshal(m, b)
}
func (m *ReadArticleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadArticleReq.Marshal(b, m, deterministic)
}
func (m *ReadArticleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadArticleReq.Merge(m, src)
}
func (m *ReadArticleReq) XXX_Size() int {
	return xxx_messageInfo_ReadArticleReq.Size(m)
}
func (m *ReadArticleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadArticleReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadArticleReq proto.InternalMessageInfo

func (m *ReadArticleReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *ReadArticleReq) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

type ReadArticleRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadArticleRsp) Reset()         { *m = ReadArticleRsp{} }
func (m *ReadArticleRsp) String() string { return proto.CompactTextString(m) }
func (*ReadArticleRsp) ProtoMessage()    {}
func (*ReadArticleRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{17}
}
func (m *ReadArticleRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadArticleRsp.Unmarshal(m, b)
}
func (m *ReadArticleRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadArticleRsp.Marshal(b, m, deterministic)
}
func (m *ReadArticleRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadArticleRsp.Merge(m, src)
}
func (m *ReadArticleRsp) XXX_Size() int {
	return xxx_messageInfo_ReadArticleRsp.Size(m)
}
func (m *ReadArticleRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadArticleRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ReadArticleRsp proto.InternalMessageInfo

type AnswerArticleReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Answer               string   `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerArticleReq) Reset()         { *m = AnswerArticleReq{} }
func (m *AnswerArticleReq) String() string { return proto.CompactTextString(m) }
func (*AnswerArticleReq) ProtoMessage()    {}
func (*AnswerArticleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{18}
}
func (m *AnswerArticleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerArticleReq.Unmarshal(m, b)
}
func (m *AnswerArticleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerArticleReq.Marshal(b, m, deterministic)
}
func (m *AnswerArticleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerArticleReq.Merge(m, src)
}
func (m *AnswerArticleReq) XXX_Size() int {
	return xxx_messageInfo_AnswerArticleReq.Size(m)
}
func (m *AnswerArticleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerArticleReq.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerArticleReq proto.InternalMessageInfo

func (m *AnswerArticleReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *AnswerArticleReq) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type AnswerArticleRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerArticleRsp) Reset()         { *m = AnswerArticleRsp{} }
func (m *AnswerArticleRsp) String() string { return proto.CompactTextString(m) }
func (*AnswerArticleRsp) ProtoMessage()    {}
func (*AnswerArticleRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{19}
}
func (m *AnswerArticleRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerArticleRsp.Unmarshal(m, b)
}
func (m *AnswerArticleRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerArticleRsp.Marshal(b, m, deterministic)
}
func (m *AnswerArticleRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerArticleRsp.Merge(m, src)
}
func (m *AnswerArticleRsp) XXX_Size() int {
	return xxx_messageInfo_AnswerArticleRsp.Size(m)
}
func (m *AnswerArticleRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerArticleRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerArticleRsp proto.InternalMessageInfo

type GetShowArticlesReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	TransParams          string   `protobuf:"bytes,3,opt,name=trans_params,json=transParams,proto3" json:"trans_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShowArticlesReq) Reset()         { *m = GetShowArticlesReq{} }
func (m *GetShowArticlesReq) String() string { return proto.CompactTextString(m) }
func (*GetShowArticlesReq) ProtoMessage()    {}
func (*GetShowArticlesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{20}
}
func (m *GetShowArticlesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShowArticlesReq.Unmarshal(m, b)
}
func (m *GetShowArticlesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShowArticlesReq.Marshal(b, m, deterministic)
}
func (m *GetShowArticlesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShowArticlesReq.Merge(m, src)
}
func (m *GetShowArticlesReq) XXX_Size() int {
	return xxx_messageInfo_GetShowArticlesReq.Size(m)
}
func (m *GetShowArticlesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShowArticlesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetShowArticlesReq proto.InternalMessageInfo

func (m *GetShowArticlesReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *GetShowArticlesReq) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *GetShowArticlesReq) GetTransParams() string {
	if m != nil {
		return m.TransParams
	}
	return ""
}

type GetShowArticlesRsp struct {
	Articles             []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	IsEnd                bool       `protobuf:"varint,2,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	TransParams          string     `protobuf:"bytes,3,opt,name=trans_params,json=transParams,proto3" json:"trans_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetShowArticlesRsp) Reset()         { *m = GetShowArticlesRsp{} }
func (m *GetShowArticlesRsp) String() string { return proto.CompactTextString(m) }
func (*GetShowArticlesRsp) ProtoMessage()    {}
func (*GetShowArticlesRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{21}
}
func (m *GetShowArticlesRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShowArticlesRsp.Unmarshal(m, b)
}
func (m *GetShowArticlesRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShowArticlesRsp.Marshal(b, m, deterministic)
}
func (m *GetShowArticlesRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShowArticlesRsp.Merge(m, src)
}
func (m *GetShowArticlesRsp) XXX_Size() int {
	return xxx_messageInfo_GetShowArticlesRsp.Size(m)
}
func (m *GetShowArticlesRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShowArticlesRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetShowArticlesRsp proto.InternalMessageInfo

func (m *GetShowArticlesRsp) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

func (m *GetShowArticlesRsp) GetIsEnd() bool {
	if m != nil {
		return m.IsEnd
	}
	return false
}

func (m *GetShowArticlesRsp) GetTransParams() string {
	if m != nil {
		return m.TransParams
	}
	return ""
}

// *******************************发布公众号接口******************************
type Woa struct {
	Owner                *User         `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	WoaId                string        `protobuf:"bytes,2,opt,name=woa_id,json=woaId,proto3" json:"woa_id,omitempty"`
	OriginId             string        `protobuf:"bytes,3,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	Name                 string        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string        `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Answer               string        `protobuf:"bytes,6,opt,name=answer,proto3" json:"answer,omitempty"`
	PublishTs            int64         `protobuf:"varint,7,opt,name=publish_ts,json=publishTs,proto3" json:"publish_ts,omitempty"`
	Status               ContentStatus `protobuf:"varint,8,opt,name=status,proto3,enum=contentoperationsvr.ContentStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Woa) Reset()         { *m = Woa{} }
func (m *Woa) String() string { return proto.CompactTextString(m) }
func (*Woa) ProtoMessage()    {}
func (*Woa) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{22}
}
func (m *Woa) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Woa.Unmarshal(m, b)
}
func (m *Woa) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Woa.Marshal(b, m, deterministic)
}
func (m *Woa) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Woa.Merge(m, src)
}
func (m *Woa) XXX_Size() int {
	return xxx_messageInfo_Woa.Size(m)
}
func (m *Woa) XXX_DiscardUnknown() {
	xxx_messageInfo_Woa.DiscardUnknown(m)
}

var xxx_messageInfo_Woa proto.InternalMessageInfo

func (m *Woa) GetOwner() *User {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Woa) GetWoaId() string {
	if m != nil {
		return m.WoaId
	}
	return ""
}

func (m *Woa) GetOriginId() string {
	if m != nil {
		return m.OriginId
	}
	return ""
}

func (m *Woa) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Woa) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Woa) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *Woa) GetPublishTs() int64 {
	if m != nil {
		return m.PublishTs
	}
	return 0
}

func (m *Woa) GetStatus() ContentStatus {
	if m != nil {
		return m.Status
	}
	return ContentStatus_ORIGIN
}

type PublishWoaReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Woa                  *Woa     `protobuf:"bytes,2,opt,name=woa,proto3" json:"woa,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishWoaReq) Reset()         { *m = PublishWoaReq{} }
func (m *PublishWoaReq) String() string { return proto.CompactTextString(m) }
func (*PublishWoaReq) ProtoMessage()    {}
func (*PublishWoaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{23}
}
func (m *PublishWoaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishWoaReq.Unmarshal(m, b)
}
func (m *PublishWoaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishWoaReq.Marshal(b, m, deterministic)
}
func (m *PublishWoaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishWoaReq.Merge(m, src)
}
func (m *PublishWoaReq) XXX_Size() int {
	return xxx_messageInfo_PublishWoaReq.Size(m)
}
func (m *PublishWoaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishWoaReq.DiscardUnknown(m)
}

var xxx_messageInfo_PublishWoaReq proto.InternalMessageInfo

func (m *PublishWoaReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *PublishWoaReq) GetWoa() *Woa {
	if m != nil {
		return m.Woa
	}
	return nil
}

type PublishWoaRsp struct {
	WoaId                string   `protobuf:"bytes,1,opt,name=woa_id,json=woaId,proto3" json:"woa_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishWoaRsp) Reset()         { *m = PublishWoaRsp{} }
func (m *PublishWoaRsp) String() string { return proto.CompactTextString(m) }
func (*PublishWoaRsp) ProtoMessage()    {}
func (*PublishWoaRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{24}
}
func (m *PublishWoaRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishWoaRsp.Unmarshal(m, b)
}
func (m *PublishWoaRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishWoaRsp.Marshal(b, m, deterministic)
}
func (m *PublishWoaRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishWoaRsp.Merge(m, src)
}
func (m *PublishWoaRsp) XXX_Size() int {
	return xxx_messageInfo_PublishWoaRsp.Size(m)
}
func (m *PublishWoaRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishWoaRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PublishWoaRsp proto.InternalMessageInfo

func (m *PublishWoaRsp) GetWoaId() string {
	if m != nil {
		return m.WoaId
	}
	return ""
}

type GetMyWoasReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Owner                *UserID  `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyWoasReq) Reset()         { *m = GetMyWoasReq{} }
func (m *GetMyWoasReq) String() string { return proto.CompactTextString(m) }
func (*GetMyWoasReq) ProtoMessage()    {}
func (*GetMyWoasReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{25}
}
func (m *GetMyWoasReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyWoasReq.Unmarshal(m, b)
}
func (m *GetMyWoasReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyWoasReq.Marshal(b, m, deterministic)
}
func (m *GetMyWoasReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyWoasReq.Merge(m, src)
}
func (m *GetMyWoasReq) XXX_Size() int {
	return xxx_messageInfo_GetMyWoasReq.Size(m)
}
func (m *GetMyWoasReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyWoasReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyWoasReq proto.InternalMessageInfo

func (m *GetMyWoasReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *GetMyWoasReq) GetOwner() *UserID {
	if m != nil {
		return m.Owner
	}
	return nil
}

type GetMyWoasRsp struct {
	Wos                  []*Woa   `protobuf:"bytes,1,rep,name=wos,proto3" json:"wos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyWoasRsp) Reset()         { *m = GetMyWoasRsp{} }
func (m *GetMyWoasRsp) String() string { return proto.CompactTextString(m) }
func (*GetMyWoasRsp) ProtoMessage()    {}
func (*GetMyWoasRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{26}
}
func (m *GetMyWoasRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyWoasRsp.Unmarshal(m, b)
}
func (m *GetMyWoasRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyWoasRsp.Marshal(b, m, deterministic)
}
func (m *GetMyWoasRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyWoasRsp.Merge(m, src)
}
func (m *GetMyWoasRsp) XXX_Size() int {
	return xxx_messageInfo_GetMyWoasRsp.Size(m)
}
func (m *GetMyWoasRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyWoasRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyWoasRsp proto.InternalMessageInfo

func (m *GetMyWoasRsp) GetWos() []*Woa {
	if m != nil {
		return m.Wos
	}
	return nil
}

type GetWoaFansReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WoaId                string   `protobuf:"bytes,2,opt,name=woa_id,json=woaId,proto3" json:"woa_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWoaFansReq) Reset()         { *m = GetWoaFansReq{} }
func (m *GetWoaFansReq) String() string { return proto.CompactTextString(m) }
func (*GetWoaFansReq) ProtoMessage()    {}
func (*GetWoaFansReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{27}
}
func (m *GetWoaFansReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWoaFansReq.Unmarshal(m, b)
}
func (m *GetWoaFansReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWoaFansReq.Marshal(b, m, deterministic)
}
func (m *GetWoaFansReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWoaFansReq.Merge(m, src)
}
func (m *GetWoaFansReq) XXX_Size() int {
	return xxx_messageInfo_GetWoaFansReq.Size(m)
}
func (m *GetWoaFansReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWoaFansReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetWoaFansReq proto.InternalMessageInfo

func (m *GetWoaFansReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *GetWoaFansReq) GetWoaId() string {
	if m != nil {
		return m.WoaId
	}
	return ""
}

type GetWoaFansRsp struct {
	Fans                 []*User  `protobuf:"bytes,1,rep,name=fans,proto3" json:"fans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWoaFansRsp) Reset()         { *m = GetWoaFansRsp{} }
func (m *GetWoaFansRsp) String() string { return proto.CompactTextString(m) }
func (*GetWoaFansRsp) ProtoMessage()    {}
func (*GetWoaFansRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{28}
}
func (m *GetWoaFansRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWoaFansRsp.Unmarshal(m, b)
}
func (m *GetWoaFansRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWoaFansRsp.Marshal(b, m, deterministic)
}
func (m *GetWoaFansRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWoaFansRsp.Merge(m, src)
}
func (m *GetWoaFansRsp) XXX_Size() int {
	return xxx_messageInfo_GetWoaFansRsp.Size(m)
}
func (m *GetWoaFansRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWoaFansRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetWoaFansRsp proto.InternalMessageInfo

func (m *GetWoaFansRsp) GetFans() []*User {
	if m != nil {
		return m.Fans
	}
	return nil
}

type SetWoaStatusReq struct {
	UserId               *UserID       `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WoaId                string        `protobuf:"bytes,2,opt,name=woa_id,json=woaId,proto3" json:"woa_id,omitempty"`
	Status               ContentStatus `protobuf:"varint,3,opt,name=status,proto3,enum=contentoperationsvr.ContentStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetWoaStatusReq) Reset()         { *m = SetWoaStatusReq{} }
func (m *SetWoaStatusReq) String() string { return proto.CompactTextString(m) }
func (*SetWoaStatusReq) ProtoMessage()    {}
func (*SetWoaStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{29}
}
func (m *SetWoaStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetWoaStatusReq.Unmarshal(m, b)
}
func (m *SetWoaStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetWoaStatusReq.Marshal(b, m, deterministic)
}
func (m *SetWoaStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetWoaStatusReq.Merge(m, src)
}
func (m *SetWoaStatusReq) XXX_Size() int {
	return xxx_messageInfo_SetWoaStatusReq.Size(m)
}
func (m *SetWoaStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetWoaStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetWoaStatusReq proto.InternalMessageInfo

func (m *SetWoaStatusReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *SetWoaStatusReq) GetWoaId() string {
	if m != nil {
		return m.WoaId
	}
	return ""
}

func (m *SetWoaStatusReq) GetStatus() ContentStatus {
	if m != nil {
		return m.Status
	}
	return ContentStatus_ORIGIN
}

type SetWoaStatusRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetWoaStatusRsp) Reset()         { *m = SetWoaStatusRsp{} }
func (m *SetWoaStatusRsp) String() string { return proto.CompactTextString(m) }
func (*SetWoaStatusRsp) ProtoMessage()    {}
func (*SetWoaStatusRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{30}
}
func (m *SetWoaStatusRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetWoaStatusRsp.Unmarshal(m, b)
}
func (m *SetWoaStatusRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetWoaStatusRsp.Marshal(b, m, deterministic)
}
func (m *SetWoaStatusRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetWoaStatusRsp.Merge(m, src)
}
func (m *SetWoaStatusRsp) XXX_Size() int {
	return xxx_messageInfo_SetWoaStatusRsp.Size(m)
}
func (m *SetWoaStatusRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetWoaStatusRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SetWoaStatusRsp proto.InternalMessageInfo

type FollowWoaReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WoaId                string   `protobuf:"bytes,2,opt,name=woa_id,json=woaId,proto3" json:"woa_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowWoaReq) Reset()         { *m = FollowWoaReq{} }
func (m *FollowWoaReq) String() string { return proto.CompactTextString(m) }
func (*FollowWoaReq) ProtoMessage()    {}
func (*FollowWoaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{31}
}
func (m *FollowWoaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowWoaReq.Unmarshal(m, b)
}
func (m *FollowWoaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowWoaReq.Marshal(b, m, deterministic)
}
func (m *FollowWoaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowWoaReq.Merge(m, src)
}
func (m *FollowWoaReq) XXX_Size() int {
	return xxx_messageInfo_FollowWoaReq.Size(m)
}
func (m *FollowWoaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowWoaReq.DiscardUnknown(m)
}

var xxx_messageInfo_FollowWoaReq proto.InternalMessageInfo

func (m *FollowWoaReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *FollowWoaReq) GetWoaId() string {
	if m != nil {
		return m.WoaId
	}
	return ""
}

type FollowWoaRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowWoaRsp) Reset()         { *m = FollowWoaRsp{} }
func (m *FollowWoaRsp) String() string { return proto.CompactTextString(m) }
func (*FollowWoaRsp) ProtoMessage()    {}
func (*FollowWoaRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{32}
}
func (m *FollowWoaRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowWoaRsp.Unmarshal(m, b)
}
func (m *FollowWoaRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowWoaRsp.Marshal(b, m, deterministic)
}
func (m *FollowWoaRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowWoaRsp.Merge(m, src)
}
func (m *FollowWoaRsp) XXX_Size() int {
	return xxx_messageInfo_FollowWoaRsp.Size(m)
}
func (m *FollowWoaRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowWoaRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FollowWoaRsp proto.InternalMessageInfo

type AnswerWoaReq struct {
	UserId               *UserID  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Answer               string   `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerWoaReq) Reset()         { *m = AnswerWoaReq{} }
func (m *AnswerWoaReq) String() string { return proto.CompactTextString(m) }
func (*AnswerWoaReq) ProtoMessage()    {}
func (*AnswerWoaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{33}
}
func (m *AnswerWoaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerWoaReq.Unmarshal(m, b)
}
func (m *AnswerWoaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerWoaReq.Marshal(b, m, deterministic)
}
func (m *AnswerWoaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerWoaReq.Merge(m, src)
}
func (m *AnswerWoaReq) XXX_Size() int {
	return xxx_messageInfo_AnswerWoaReq.Size(m)
}
func (m *AnswerWoaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerWoaReq.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerWoaReq proto.InternalMessageInfo

func (m *AnswerWoaReq) GetUserId() *UserID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *AnswerWoaReq) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type AnswerWoaRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerWoaRsp) Reset()         { *m = AnswerWoaRsp{} }
func (m *AnswerWoaRsp) String() string { return proto.CompactTextString(m) }
func (*AnswerWoaRsp) ProtoMessage()    {}
func (*AnswerWoaRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3a3127d9784c00, []int{34}
}
func (m *AnswerWoaRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerWoaRsp.Unmarshal(m, b)
}
func (m *AnswerWoaRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerWoaRsp.Marshal(b, m, deterministic)
}
func (m *AnswerWoaRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerWoaRsp.Merge(m, src)
}
func (m *AnswerWoaRsp) XXX_Size() int {
	return xxx_messageInfo_AnswerWoaRsp.Size(m)
}
func (m *AnswerWoaRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerWoaRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerWoaRsp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("contentoperationsvr.ContentStatus", ContentStatus_name, ContentStatus_value)
	proto.RegisterType((*UserID)(nil), "contentoperationsvr.UserID")
	proto.RegisterType((*User)(nil), "contentoperationsvr.User")
	proto.RegisterType((*LoginReq)(nil), "contentoperationsvr.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "contentoperationsvr.LoginRsp")
	proto.RegisterType((*UserInfo)(nil), "contentoperationsvr.UserInfo")
	proto.RegisterType((*GetUserInfoReq)(nil), "contentoperationsvr.GetUserInfoReq")
	proto.RegisterType((*GetUserInfoRsp)(nil), "contentoperationsvr.GetUserInfoRsp")
	proto.RegisterType((*Article)(nil), "contentoperationsvr.Article")
	proto.RegisterType((*PublishArticleReq)(nil), "contentoperationsvr.PublishArticleReq")
	proto.RegisterType((*PublishArticleRsp)(nil), "contentoperationsvr.PublishArticleRsp")
	proto.RegisterType((*GetMyArticlesReq)(nil), "contentoperationsvr.GetMyArticlesReq")
	proto.RegisterType((*GetMyArticlesRsp)(nil), "contentoperationsvr.GetMyArticlesRsp")
	proto.RegisterType((*GetArticleReadersReq)(nil), "contentoperationsvr.GetArticleReadersReq")
	proto.RegisterType((*GetArticleReadersRsp)(nil), "contentoperationsvr.GetArticleReadersRsp")
	proto.RegisterType((*SetArticleStatusReq)(nil), "contentoperationsvr.SetArticleStatusReq")
	proto.RegisterType((*SetArticleStatusRsp)(nil), "contentoperationsvr.SetArticleStatusRsp")
	proto.RegisterType((*ReadArticleReq)(nil), "contentoperationsvr.ReadArticleReq")
	proto.RegisterType((*ReadArticleRsp)(nil), "contentoperationsvr.ReadArticleRsp")
	proto.RegisterType((*AnswerArticleReq)(nil), "contentoperationsvr.AnswerArticleReq")
	proto.RegisterType((*AnswerArticleRsp)(nil), "contentoperationsvr.AnswerArticleRsp")
	proto.RegisterType((*GetShowArticlesReq)(nil), "contentoperationsvr.GetShowArticlesReq")
	proto.RegisterType((*GetShowArticlesRsp)(nil), "contentoperationsvr.GetShowArticlesRsp")
	proto.RegisterType((*Woa)(nil), "contentoperationsvr.Woa")
	proto.RegisterType((*PublishWoaReq)(nil), "contentoperationsvr.PublishWoaReq")
	proto.RegisterType((*PublishWoaRsp)(nil), "contentoperationsvr.PublishWoaRsp")
	proto.RegisterType((*GetMyWoasReq)(nil), "contentoperationsvr.GetMyWoasReq")
	proto.RegisterType((*GetMyWoasRsp)(nil), "contentoperationsvr.GetMyWoasRsp")
	proto.RegisterType((*GetWoaFansReq)(nil), "contentoperationsvr.GetWoaFansReq")
	proto.RegisterType((*GetWoaFansRsp)(nil), "contentoperationsvr.GetWoaFansRsp")
	proto.RegisterType((*SetWoaStatusReq)(nil), "contentoperationsvr.SetWoaStatusReq")
	proto.RegisterType((*SetWoaStatusRsp)(nil), "contentoperationsvr.SetWoaStatusRsp")
	proto.RegisterType((*FollowWoaReq)(nil), "contentoperationsvr.FollowWoaReq")
	proto.RegisterType((*FollowWoaRsp)(nil), "contentoperationsvr.FollowWoaRsp")
	proto.RegisterType((*AnswerWoaReq)(nil), "contentoperationsvr.AnswerWoaReq")
	proto.RegisterType((*AnswerWoaRsp)(nil), "contentoperationsvr.AnswerWoaRsp")
}

func init() { proto.RegisterFile("contentoperationsvr.proto", fileDescriptor_ce3a3127d9784c00) }

var fileDescriptor_ce3a3127d9784c00 = []byte{
	// 1529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0x4f, 0x6f, 0x1b, 0x37,
	0x16, 0x5f, 0x5a, 0xd6, 0xbf, 0xe7, 0x3f, 0x51, 0xe8, 0x64, 0x23, 0x4f, 0x12, 0xac, 0xc3, 0xdd,
	0x4d, 0xbc, 0x01, 0x1c, 0x21, 0xde, 0x60, 0xb1, 0xeb, 0xdd, 0x4d, 0x62, 0x27, 0xb6, 0xa2, 0xc2,
	0xb1, 0x03, 0xd9, 0x81, 0x81, 0x36, 0xa8, 0xca, 0x48, 0x8c, 0x3c, 0x8d, 0x34, 0x64, 0x86, 0x23,
	0xab, 0x39, 0x15, 0x2d, 0xd0, 0xa2, 0xe8, 0xb5, 0x97, 0xb6, 0x29, 0xd0, 0x1e, 0x8a, 0xfe, 0x41,
	0x0f, 0xbd, 0xf4, 0xd0, 0x7b, 0x3f, 0x42, 0xbf, 0x42, 0x3f, 0x45, 0x4f, 0x05, 0x39, 0x1c, 0x79,
	0x24, 0xcf, 0x58, 0xb2, 0x26, 0x45, 0x6f, 0x9c, 0xf7, 0x7e, 0x7c, 0xfc, 0xf1, 0xf1, 0xf1, 0xf1,
	0x27, 0xc1, 0x7c, 0x9d, 0x3b, 0x1e, 0x73, 0x3c, 0x2e, 0x98, 0x4b, 0x3d, 0x9b, 0x3b, 0xf2, 0xc0,
	0xbd, 0x26, 0x5c, 0xee, 0x71, 0x3c, 0x17, 0xe1, 0xb2, 0x2e, 0x34, 0x39, 0x6f, 0xb6, 0x58, 0x89,
	0x0a, 0xbb, 0x44, 0x1d, 0x87, 0x7b, 0xbe, 0xc7, 0x9f, 0x62, 0x9d, 0x3b, 0xa0, 0x2d, 0xbb, 0x41,
	0x3d, 0x56, 0x0a, 0x06, 0xc6, 0x71, 0xa6, 0xc9, 0x9b, 0x5c, 0x0f, 0x4b, 0x6a, 0xe4, 0x5b, 0xc9,
	0xeb, 0x90, 0x79, 0x28, 0x99, 0x5b, 0xb9, 0x8b, 0xe7, 0x21, 0xd7, 0x71, 0x6c, 0xee, 0xd4, 0xec,
	0x46, 0x11, 0x2d, 0xa0, 0xc5, 0x7c, 0x35, 0xab, 0xbf, 0x2b, 0x0d, 0xfc, 0x67, 0xc8, 0x70, 0xc1,
	0x1c, 0xbb, 0x51, 0x9c, 0xd0, 0x0e, 0xf3, 0x85, 0x2f, 0xc1, 0x34, 0xad, 0xd7, 0x99, 0x94, 0x35,
	0x8f, 0x3f, 0x65, 0x4e, 0x31, 0xa5, 0xbd, 0x53, 0xbe, 0x6d, 0x57, 0x99, 0x88, 0x07, 0x93, 0x2a,
	0x3e, 0xbe, 0x01, 0xd9, 0x8e, 0x64, 0x6e, 0x10, 0x7c, 0x6a, 0xf9, 0xfc, 0xb5, 0xa8, 0x6d, 0xfb,
	0x5c, 0xaa, 0x19, 0x85, 0xad, 0x34, 0x14, 0xa7, 0x7d, 0x46, 0x1b, 0xb5, 0x8e, 0xdb, 0x32, 0x4b,
	0x67, 0xd5, 0xf7, 0x43, 0xb7, 0x85, 0xcf, 0x43, 0xde, 0xb1, 0xeb, 0x4f, 0x6b, 0x0e, 0x6d, 0x33,
	0xb3, 0x70, 0x4e, 0x19, 0xb6, 0x68, 0x9b, 0x91, 0x2b, 0x90, 0xdb, 0xe4, 0x4d, 0xdb, 0xa9, 0xb2,
	0x67, 0xf8, 0x3c, 0x4c, 0xd6, 0x79, 0x83, 0xf9, 0x7b, 0x5a, 0xcb, 0xfe, 0xba, 0x36, 0xe9, 0x4e,
	0x14, 0x50, 0x55, 0x1b, 0xc9, 0xed, 0x00, 0x28, 0xc5, 0x78, 0x14, 0xc9, 0xb7, 0x08, 0x72, 0xda,
	0xe4, 0x3c, 0xe1, 0x78, 0x09, 0x26, 0x95, 0xd9, 0xcc, 0x9f, 0x8f, 0x9d, 0x5f, 0xd5, 0x30, 0xfc,
	0x17, 0x98, 0xa2, 0xae, 0x67, 0xd7, 0x5b, 0xac, 0xe6, 0x74, 0xda, 0x7a, 0x87, 0xe9, 0x2a, 0x18,
	0xd3, 0x56, 0xa7, 0x8d, 0xcf, 0x41, 0xb6, 0xcb, 0xa9, 0x76, 0xa6, 0xb4, 0x33, 0xd3, 0xe5, 0x54,
	0x39, 0xe6, 0x21, 0xe7, 0xaa, 0xc4, 0x28, 0xcf, 0xa4, 0xf6, 0x64, 0xd5, 0xb7, 0x71, 0x3d, 0xa1,
	0x8e, 0xd4, 0xae, 0xb4, 0xef, 0x52, 0xdf, 0x5b, 0x9d, 0x36, 0xd9, 0x80, 0xd9, 0x32, 0xf3, 0x02,
	0xb6, 0x2a, 0x39, 0xe3, 0xed, 0x79, 0xb3, 0x3f, 0x8e, 0x14, 0x78, 0x05, 0xf2, 0x7e, 0x1c, 0xe7,
	0x09, 0x37, 0x91, 0x2e, 0xc6, 0x47, 0x52, 0x93, 0x72, 0x1d, 0x33, 0x22, 0x1f, 0x4e, 0x40, 0x76,
	0xd5, 0xdf, 0x33, 0xbe, 0x0e, 0x19, 0xda, 0xf1, 0xf6, 0xf9, 0x08, 0x29, 0x34, 0x40, 0x7c, 0x11,
	0x82, 0x8c, 0xd5, 0x7a, 0x05, 0x9a, 0x37, 0x96, 0x4a, 0x03, 0x9f, 0x81, 0xb4, 0x67, 0x7b, 0xad,
	0xa0, 0x46, 0xfc, 0x0f, 0x8c, 0x61, 0xb2, 0xc1, 0x64, 0x5d, 0xe7, 0x2e, 0x5f, 0xd5, 0x63, 0x5c,
	0x80, 0x94, 0xaa, 0xb3, 0xb4, 0x36, 0xa9, 0xa1, 0xaa, 0x7b, 0xea, 0xc8, 0x2e, 0x73, 0x8b, 0x19,
	0xbf, 0xee, 0xfd, 0x2f, 0xb5, 0xa4, 0xe8, 0x3c, 0x6e, 0xd9, 0x72, 0xbf, 0xe6, 0xc9, 0x62, 0x76,
	0x01, 0x2d, 0xa6, 0xaa, 0x79, 0x63, 0xd9, 0x95, 0x78, 0x05, 0x32, 0xd2, 0xa3, 0x5e, 0x47, 0x16,
	0x73, 0x0b, 0x68, 0x71, 0x76, 0x99, 0x44, 0x6e, 0xe2, 0x8e, 0x6f, 0xdb, 0xd1, 0xc8, 0xaa, 0x99,
	0x41, 0xde, 0x41, 0x70, 0xfa, 0x81, 0x1f, 0xc9, 0xe4, 0x64, 0xec, 0x63, 0xc2, 0xff, 0x82, 0xac,
	0xc9, 0x83, 0x4e, 0xcb, 0xd4, 0xf2, 0x85, 0xc8, 0x59, 0xc1, 0x3a, 0x01, 0x98, 0x2c, 0x1f, 0xa1,
	0x20, 0xc5, 0x40, 0x9a, 0xd1, 0x40, 0x9a, 0xc9, 0x3d, 0x28, 0x94, 0x99, 0x77, 0xff, 0xb9, 0x99,
	0x21, 0x93, 0x14, 0xd7, 0x40, 0x24, 0x29, 0xf0, 0xbf, 0x21, 0x67, 0x96, 0x92, 0x45, 0xb4, 0x90,
	0x1a, 0xba, 0x95, 0x1e, 0x9a, 0x3c, 0x85, 0x33, 0x65, 0xe6, 0xf5, 0x52, 0x49, 0x1b, 0xcc, 0x1d,
	0x9f, 0xdb, 0x90, 0x5a, 0x23, 0xe5, 0xa8, 0xc5, 0xa4, 0xc0, 0x25, 0x48, 0xab, 0x00, 0x01, 0xf7,
	0x63, 0x8a, 0xda, 0xc7, 0x91, 0xaf, 0x10, 0xcc, 0xed, 0xf4, 0x22, 0x99, 0x12, 0xf9, 0x9d, 0x58,
	0x87, 0xca, 0x35, 0x75, 0xe2, 0x72, 0x3d, 0x1b, 0xc1, 0x53, 0x0a, 0xc2, 0x60, 0x56, 0x6d, 0x3f,
	0x71, 0x05, 0x0f, 0xc9, 0x77, 0xa1, 0x7f, 0x19, 0x29, 0xc8, 0x1b, 0x50, 0x58, 0xd5, 0x77, 0x34,
	0xf1, 0xd2, 0x87, 0x77, 0x3f, 0x15, 0xbe, 0xfb, 0x04, 0x0f, 0xae, 0x20, 0x05, 0x79, 0x1b, 0x70,
	0x99, 0x79, 0x3b, 0xfb, 0xbc, 0x9b, 0xb8, 0xfc, 0x55, 0x17, 0x3a, 0x7c, 0x0b, 0xd4, 0x50, 0xbd,
	0xb2, 0x9e, 0xab, 0x3a, 0xba, 0xa0, 0x2e, 0x6d, 0xcb, 0xe0, 0x95, 0xd5, 0xb6, 0x07, 0xda, 0x44,
	0x3e, 0x40, 0x47, 0x19, 0x24, 0xb9, 0x36, 0xf8, 0x2c, 0x64, 0x6c, 0x59, 0x63, 0x8e, 0x9f, 0xf4,
	0x5c, 0x35, 0x6d, 0xcb, 0x75, 0xa7, 0x31, 0x0a, 0x95, 0xf7, 0x26, 0x20, 0xb5, 0xc7, 0xa9, 0xaa,
	0x79, 0xde, 0x75, 0x46, 0x79, 0x0b, 0x7d, 0x9c, 0x5a, 0x52, 0xbd, 0x75, 0xbd, 0x73, 0x4e, 0x77,
	0x39, 0xad, 0x34, 0xd4, 0x3b, 0xcf, 0x5d, 0xbb, 0x69, 0x6b, 0x5d, 0x62, 0xde, 0x79, 0xdf, 0x50,
	0x69, 0xa8, 0x36, 0xae, 0xdf, 0x7f, 0xd3, 0xc6, 0xd5, 0xb8, 0xd7, 0xda, 0xd3, 0xa1, 0xd6, 0xfe,
	0x07, 0x34, 0xf2, 0x67, 0x30, 0x63, 0x9a, 0xe8, 0x1e, 0xa7, 0xe3, 0x97, 0xc3, 0x55, 0x48, 0x75,
	0x39, 0x35, 0xfd, 0xbb, 0x18, 0x39, 0x43, 0xc5, 0x57, 0x20, 0x72, 0xb9, 0x6f, 0x49, 0x29, 0x42,
	0x29, 0x45, 0xa1, 0x94, 0x92, 0x2e, 0x4c, 0xeb, 0x0e, 0xbb, 0xc7, 0x69, 0x82, 0x42, 0xbd, 0x1e,
	0x1c, 0xf0, 0xc4, 0xf0, 0x39, 0x3e, 0x92, 0xac, 0x84, 0x17, 0x96, 0xc2, 0xdf, 0x5c, 0x50, 0x9a,
	0xc7, 0x6e, 0x4e, 0x92, 0x47, 0x30, 0x53, 0x66, 0xde, 0x1e, 0xa7, 0x1b, 0xd4, 0x49, 0xc0, 0x3a,
	0xba, 0xca, 0xc8, 0xcd, 0xbe, 0xe8, 0x52, 0x28, 0x25, 0xa7, 0x54, 0xd3, 0xf0, 0x8e, 0xad, 0x61,
	0xe4, 0x53, 0x04, 0xa7, 0x76, 0x74, 0x80, 0xa4, 0xcd, 0x3a, 0xe6, 0x1a, 0x24, 0x69, 0xd2, 0xa7,
	0x07, 0xb8, 0x49, 0x41, 0x5e, 0x83, 0xe9, 0x0d, 0xde, 0x6a, 0xf1, 0x6e, 0xa2, 0xe2, 0x8c, 0x49,
	0xe6, 0x6c, 0x38, 0xb8, 0x14, 0xe4, 0x11, 0x4c, 0xfb, 0x2d, 0x33, 0xd1, 0x62, 0x71, 0x0d, 0x79,
	0x36, 0x1c, 0x5d, 0x8a, 0xab, 0x15, 0x98, 0xe9, 0x4b, 0x03, 0x06, 0xc8, 0x6c, 0x57, 0x2b, 0xe5,
	0xca, 0x56, 0xe1, 0x4f, 0x7a, 0xbc, 0xb5, 0x59, 0xd9, 0x5a, 0x2f, 0x20, 0x3c, 0x05, 0xd9, 0xed,
	0x8d, 0x0d, 0xfd, 0x31, 0xa1, 0x1c, 0x77, 0xd7, 0x37, 0xd7, 0x77, 0xd7, 0x0b, 0x29, 0x9c, 0x85,
	0xd4, 0xee, 0xf6, 0x83, 0xc2, 0xe4, 0xf2, 0x4f, 0x73, 0x30, 0x67, 0x62, 0x6d, 0x07, 0xcc, 0x76,
	0x0e, 0x5c, 0xfc, 0x3e, 0x82, 0xb4, 0xfe, 0xd9, 0x80, 0xa3, 0x45, 0x6e, 0xf0, 0xdb, 0xc3, 0x3a,
	0xce, 0x2d, 0x05, 0xb9, 0xf5, 0xee, 0xcf, 0xbf, 0x7c, 0x34, 0xf1, 0x1f, 0x72, 0xa3, 0x64, 0x60,
	0x4b, 0x3d, 0xdc, 0x92, 0x70, 0xf9, 0x5b, 0xcf, 0x23, 0xec, 0xf2, 0xc0, 0x2d, 0xb5, 0x54, 0x80,
	0x15, 0x74, 0x15, 0x7f, 0x81, 0x60, 0x2a, 0xa4, 0xc4, 0xf1, 0x5f, 0x23, 0xd7, 0xeb, 0xd7, 0xfc,
	0xd6, 0x70, 0x90, 0x14, 0xa4, 0xac, 0xa9, 0xad, 0x92, 0xff, 0x9d, 0x90, 0x5a, 0x93, 0x79, 0x4b,
	0xea, 0xc0, 0x96, 0xd4, 0x2f, 0x01, 0x45, 0xf1, 0x3b, 0x04, 0xb3, 0xfd, 0x6a, 0x12, 0x5f, 0x8e,
	0x24, 0x70, 0x44, 0xf5, 0x5a, 0x23, 0xe1, 0xa4, 0x20, 0x15, 0xcd, 0xf5, 0x0e, 0xb9, 0x79, 0x42,
	0xae, 0xa6, 0xd1, 0x2f, 0x99, 0x57, 0x4f, 0xb1, 0xfd, 0x01, 0x41, 0x61, 0x50, 0xd0, 0xe0, 0xc5,
	0x48, 0x1e, 0x11, 0xfa, 0xcc, 0x1a, 0x11, 0x29, 0x05, 0xd9, 0xd4, 0x9c, 0x37, 0xc8, 0xea, 0x09,
	0x39, 0x4b, 0xe6, 0x05, 0x7c, 0x97, 0xfc, 0xeb, 0xad, 0x68, 0x7f, 0x83, 0x74, 0xff, 0x3a, 0x14,
	0xcd, 0xf8, 0xef, 0x71, 0x87, 0xdc, 0x27, 0xd1, 0xad, 0x51, 0x60, 0x09, 0x32, 0xac, 0xaa, 0xa1,
	0xfd, 0x3c, 0x20, 0xac, 0xa9, 0xfe, 0x88, 0xe0, 0xf4, 0x11, 0x91, 0x8c, 0xff, 0x11, 0xc7, 0xe3,
	0x88, 0x72, 0xb7, 0x46, 0x85, 0x4a, 0x41, 0xee, 0x6b, 0xda, 0x65, 0xb2, 0x36, 0x06, 0xed, 0x20,
	0xc9, 0xae, 0x1f, 0x4e, 0x51, 0xff, 0x1c, 0xc1, 0x54, 0x48, 0x6f, 0xc6, 0xdc, 0xb6, 0x7e, 0xe1,
	0x6b, 0x0d, 0x07, 0x49, 0x41, 0x36, 0x34, 0xd1, 0xdb, 0xe4, 0xbf, 0x27, 0x24, 0xaa, 0xc8, 0x85,
	0xcb, 0xf7, 0x6b, 0x04, 0x33, 0x7d, 0xea, 0x34, 0xa6, 0x0e, 0x06, 0x35, 0xb2, 0x35, 0x0a, 0x4c,
	0x0a, 0x72, 0x4f, 0xf3, 0x5c, 0x23, 0xff, 0x3f, 0x21, 0x4f, 0xbf, 0x55, 0x87, 0x99, 0x7e, 0x8f,
	0xe0, 0xd4, 0x80, 0x62, 0xc5, 0x57, 0xe2, 0x4e, 0x76, 0x40, 0x59, 0x5b, 0xa3, 0x01, 0xa5, 0x20,
	0xaf, 0x68, 0xbe, 0x77, 0xc9, 0xad, 0x31, 0x0a, 0x40, 0xee, 0xf3, 0x6e, 0x98, 0xf1, 0x0b, 0x04,
	0x70, 0x28, 0xaf, 0x30, 0x39, 0xae, 0x39, 0xf9, 0x0f, 0x9d, 0x35, 0x14, 0x23, 0x05, 0x59, 0xd7,
	0x14, 0x6f, 0x91, 0x95, 0x31, 0x9b, 0x57, 0x97, 0x53, 0xc5, 0xee, 0x4b, 0x04, 0xd3, 0xe1, 0x47,
	0x1e, 0xff, 0x2d, 0xae, 0x15, 0x85, 0x35, 0x8a, 0x35, 0x02, 0x2a, 0xc1, 0xb1, 0xab, 0x66, 0xd5,
	0xe5, 0x34, 0xd4, 0xa8, 0x3e, 0x46, 0x90, 0xef, 0x49, 0x40, 0x7c, 0x29, 0xbe, 0xfb, 0x18, 0x6d,
	0x6a, 0x0d, 0x83, 0x24, 0xc8, 0xa0, 0x69, 0x4e, 0x5d, 0x4e, 0x35, 0xb5, 0xcf, 0x10, 0xc0, 0xa1,
	0x06, 0x8c, 0x39, 0xdf, 0x3e, 0x09, 0x6a, 0x0d, 0xc5, 0x24, 0xb8, 0xda, 0x4d, 0x93, 0x3b, 0x25,
	0x2f, 0x15, 0xbd, 0x4f, 0x10, 0xe4, 0x7b, 0xaa, 0x2a, 0x26, 0x73, 0x61, 0x49, 0x67, 0x0d, 0x83,
	0xbc, 0xc4, 0xb6, 0xf3, 0x02, 0x41, 0xbe, 0xa7, 0xc1, 0x62, 0xb8, 0x85, 0x15, 0xa0, 0x35, 0x0c,
	0xf2, 0x32, 0x5b, 0xcd, 0x5a, 0xe5, 0xd5, 0x72, 0xd3, 0xf6, 0xf6, 0x3b, 0x8f, 0xaf, 0xd5, 0x79,
	0xbb, 0xf4, 0x26, 0x73, 0x24, 0x73, 0x9a, 0x1d, 0x5e, 0xf2, 0xff, 0x0b, 0x3f, 0x1a, 0xa5, 0x4d,
	0xa5, 0xc7, 0xdc, 0x52, 0x04, 0xc3, 0xc7, 0x19, 0x3d, 0xe7, 0x9f, 0xbf, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xc2, 0x1c, 0xaa, 0x44, 0xb3, 0x17, 0x00, 0x00,
}
