// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: outerproxy.proto

package outerproxy

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// *******************************创建聊天接口******************************
type ChatCompletionMessage struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatCompletionMessage) Reset()         { *m = ChatCompletionMessage{} }
func (m *ChatCompletionMessage) String() string { return proto.CompactTextString(m) }
func (*ChatCompletionMessage) ProtoMessage()    {}
func (*ChatCompletionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_3861d6a66bc365af, []int{0}
}
func (m *ChatCompletionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatCompletionMessage.Unmarshal(m, b)
}
func (m *ChatCompletionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatCompletionMessage.Marshal(b, m, deterministic)
}
func (m *ChatCompletionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatCompletionMessage.Merge(m, src)
}
func (m *ChatCompletionMessage) XXX_Size() int {
	return xxx_messageInfo_ChatCompletionMessage.Size(m)
}
func (m *ChatCompletionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatCompletionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatCompletionMessage proto.InternalMessageInfo

func (m *ChatCompletionMessage) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ChatCompletionMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateChatCompletionReq struct {
	Model                string                   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Userid               string                   `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Messages             []*ChatCompletionMessage `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CreateChatCompletionReq) Reset()         { *m = CreateChatCompletionReq{} }
func (m *CreateChatCompletionReq) String() string { return proto.CompactTextString(m) }
func (*CreateChatCompletionReq) ProtoMessage()    {}
func (*CreateChatCompletionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3861d6a66bc365af, []int{1}
}
func (m *CreateChatCompletionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChatCompletionReq.Unmarshal(m, b)
}
func (m *CreateChatCompletionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChatCompletionReq.Marshal(b, m, deterministic)
}
func (m *CreateChatCompletionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChatCompletionReq.Merge(m, src)
}
func (m *CreateChatCompletionReq) XXX_Size() int {
	return xxx_messageInfo_CreateChatCompletionReq.Size(m)
}
func (m *CreateChatCompletionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChatCompletionReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChatCompletionReq proto.InternalMessageInfo

func (m *CreateChatCompletionReq) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *CreateChatCompletionReq) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *CreateChatCompletionReq) GetMessages() []*ChatCompletionMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type CreateChatCompletionRsp struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChatCompletionRsp) Reset()         { *m = CreateChatCompletionRsp{} }
func (m *CreateChatCompletionRsp) String() string { return proto.CompactTextString(m) }
func (*CreateChatCompletionRsp) ProtoMessage()    {}
func (*CreateChatCompletionRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3861d6a66bc365af, []int{2}
}
func (m *CreateChatCompletionRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChatCompletionRsp.Unmarshal(m, b)
}
func (m *CreateChatCompletionRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChatCompletionRsp.Marshal(b, m, deterministic)
}
func (m *CreateChatCompletionRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChatCompletionRsp.Merge(m, src)
}
func (m *CreateChatCompletionRsp) XXX_Size() int {
	return xxx_messageInfo_CreateChatCompletionRsp.Size(m)
}
func (m *CreateChatCompletionRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChatCompletionRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChatCompletionRsp proto.InternalMessageInfo

func (m *CreateChatCompletionRsp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// *******************************创建图片接口******************************
type CreateImageReq struct {
	Prompt               string   `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateImageReq) Reset()         { *m = CreateImageReq{} }
func (m *CreateImageReq) String() string { return proto.CompactTextString(m) }
func (*CreateImageReq) ProtoMessage()    {}
func (*CreateImageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3861d6a66bc365af, []int{3}
}
func (m *CreateImageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateImageReq.Unmarshal(m, b)
}
func (m *CreateImageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateImageReq.Marshal(b, m, deterministic)
}
func (m *CreateImageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateImageReq.Merge(m, src)
}
func (m *CreateImageReq) XXX_Size() int {
	return xxx_messageInfo_CreateImageReq.Size(m)
}
func (m *CreateImageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateImageReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateImageReq proto.InternalMessageInfo

func (m *CreateImageReq) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

type CreateImageRsp struct {
	B64Json              string   `protobuf:"bytes,1,opt,name=b64_json,json=b64Json,proto3" json:"b64_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateImageRsp) Reset()         { *m = CreateImageRsp{} }
func (m *CreateImageRsp) String() string { return proto.CompactTextString(m) }
func (*CreateImageRsp) ProtoMessage()    {}
func (*CreateImageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3861d6a66bc365af, []int{4}
}
func (m *CreateImageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateImageRsp.Unmarshal(m, b)
}
func (m *CreateImageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateImageRsp.Marshal(b, m, deterministic)
}
func (m *CreateImageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateImageRsp.Merge(m, src)
}
func (m *CreateImageRsp) XXX_Size() int {
	return xxx_messageInfo_CreateImageRsp.Size(m)
}
func (m *CreateImageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateImageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateImageRsp proto.InternalMessageInfo

func (m *CreateImageRsp) GetB64Json() string {
	if m != nil {
		return m.B64Json
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatCompletionMessage)(nil), "outerproxy.ChatCompletionMessage")
	proto.RegisterType((*CreateChatCompletionReq)(nil), "outerproxy.CreateChatCompletionReq")
	proto.RegisterType((*CreateChatCompletionRsp)(nil), "outerproxy.CreateChatCompletionRsp")
	proto.RegisterType((*CreateImageReq)(nil), "outerproxy.CreateImageReq")
	proto.RegisterType((*CreateImageRsp)(nil), "outerproxy.CreateImageRsp")
}

func init() { proto.RegisterFile("outerproxy.proto", fileDescriptor_3861d6a66bc365af) }

var fileDescriptor_3861d6a66bc365af = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb5, 0x6e, 0x9b, 0xa6, 0x5b, 0x09, 0x55, 0xab, 0x42, 0x83, 0x01, 0xd1, 0x9a, 0x4b,
	0x54, 0x94, 0xac, 0xd4, 0x56, 0x3d, 0xe4, 0xc0, 0x1f, 0x07, 0x84, 0x82, 0x84, 0x2a, 0x85, 0x03,
	0x12, 0x17, 0xb4, 0x71, 0x46, 0x1b, 0x57, 0xf6, 0xce, 0xb2, 0xbb, 0x89, 0xe0, 0xca, 0x99, 0x13,
	0xbc, 0x01, 0x6f, 0xc0, 0x8b, 0x70, 0xe1, 0x15, 0x78, 0x8a, 0x9e, 0x90, 0xd7, 0x71, 0x13, 0xb7,
	0xa9, 0x90, 0xb8, 0x8d, 0xbf, 0x99, 0xf9, 0xe9, 0xfb, 0x46, 0x5e, 0xba, 0x83, 0x53, 0x07, 0x46,
	0x1b, 0xfc, 0xf4, 0xb9, 0xab, 0x0d, 0x3a, 0x64, 0x74, 0xa1, 0x84, 0xf7, 0x25, 0xa2, 0xcc, 0x80,
	0x0b, 0x9d, 0x72, 0xa1, 0x14, 0x3a, 0xe1, 0x52, 0x54, 0xb6, 0x9c, 0x0c, 0xf7, 0x66, 0x22, 0x4b,
	0xc7, 0xc2, 0x01, 0xaf, 0x8a, 0x79, 0x63, 0x57, 0xa2, 0x44, 0x5f, 0xf2, 0xa2, 0x2a, 0xd5, 0xe8,
	0x1d, 0xbd, 0xdd, 0x9f, 0x08, 0xd7, 0xc7, 0x5c, 0x67, 0x50, 0x70, 0xde, 0x80, 0xb5, 0x42, 0x02,
	0xbb, 0x47, 0xd7, 0x0d, 0x66, 0xd0, 0x22, 0xfb, 0xa4, 0xbd, 0x15, 0x6f, 0x5e, 0xc4, 0xeb, 0x26,
	0xd8, 0x21, 0x43, 0x2f, 0xb2, 0x03, 0xba, 0x99, 0xa0, 0x72, 0xa0, 0x5c, 0x2b, 0xa8, 0xf7, 0x2b,
	0x3d, 0xfa, 0x41, 0xe8, 0x5e, 0xdf, 0x80, 0x70, 0x50, 0xe7, 0x0f, 0xe1, 0x23, 0x7b, 0x40, 0x37,
	0x72, 0x1c, 0x43, 0x76, 0x15, 0x5e, 0xaa, 0xec, 0x21, 0x6d, 0x4c, 0x2d, 0x98, 0x74, 0x7c, 0x15,
	0x3e, 0x97, 0xd9, 0x2b, 0xda, 0xcc, 0x4b, 0x9b, 0xb6, 0xb5, 0xb6, 0xbf, 0xd6, 0xde, 0x3e, 0x3a,
	0xe8, 0x2e, 0x9d, 0x6c, 0x65, 0xa0, 0xb8, 0x79, 0x11, 0x6f, 0x7c, 0x23, 0x41, 0x93, 0x0c, 0x2f,
	0x97, 0xa3, 0xe3, 0x1b, 0x3c, 0x5a, 0xcd, 0x5a, 0x8b, 0x88, 0xde, 0xe5, 0x22, 0x59, 0x9b, 0xde,
	0x2a, 0x97, 0x06, 0xb9, 0x90, 0x50, 0xe4, 0xb9, 0x43, 0x1b, 0xda, 0x60, 0xae, 0xab, 0xd1, 0xf9,
	0x57, 0xf4, 0xb8, 0x3e, 0x69, 0x35, 0xbb, 0x4b, 0x9b, 0xa3, 0xd3, 0x93, 0x0f, 0xe7, 0x16, 0x55,
	0x85, 0x1d, 0x9d, 0x9e, 0xbc, 0xb6, 0xa8, 0x8e, 0x7e, 0x05, 0x74, 0xeb, 0x4c, 0x83, 0x7a, 0x3e,
	0x78, 0x3b, 0x33, 0xec, 0x27, 0xa1, 0xbb, 0xab, 0xac, 0xb1, 0x47, 0xb5, 0xa4, 0xab, 0x0f, 0x1c,
	0xfe, 0x7b, 0xc8, 0xea, 0xe8, 0xec, 0xcb, 0xef, 0x3f, 0xdf, 0x83, 0x41, 0xf4, 0x82, 0xcf, 0x93,
	0x75, 0x50, 0x83, 0xf1, 0x3f, 0x53, 0xc7, 0x6f, 0xf2, 0x05, 0xa4, 0x68, 0x29, 0x91, 0xda, 0x99,
	0xe1, 0x89, 0xc7, 0x75, 0x92, 0x89, 0x70, 0x9d, 0xe4, 0x12, 0xd8, 0x23, 0x87, 0xec, 0x2b, 0xa1,
	0xdb, 0x4b, 0x79, 0x59, 0x78, 0xdd, 0x45, 0x75, 0xb2, 0xf0, 0xc6, 0x9e, 0xd5, 0xd1, 0x4b, 0x6f,
	0xec, 0x69, 0xd4, 0xfb, 0x2f, 0x63, 0x69, 0x81, 0xe9, 0x91, 0xc3, 0xf8, 0xd9, 0xfb, 0x27, 0x32,
	0x75, 0x93, 0xe9, 0xa8, 0x9b, 0x60, 0xce, 0xcf, 0x41, 0x59, 0x50, 0x72, 0x8a, 0xbc, 0x7c, 0x03,
	0xd7, 0xd1, 0xb9, 0xb0, 0x0e, 0xcc, 0x12, 0x7b, 0xd4, 0xf0, 0xa3, 0xc7, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x8b, 0x6d, 0x4d, 0x63, 0x90, 0x03, 0x00, 0x00,
}
