// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: wxpay.proto

package wxpay

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TransactionsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TransactionsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransactionsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransactionsReqMultiError, or nil if none found.
func (m *TransactionsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *TransactionsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FromUserName

	// no validation rules for VipType

	if len(errors) > 0 {
		return TransactionsReqMultiError(errors)
	}

	return nil
}

// TransactionsReqMultiError is an error wrapping multiple validation errors
// returned by TransactionsReq.ValidateAll() if the designated constraints
// aren't met.
type TransactionsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransactionsReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransactionsReqMultiError) AllErrors() []error { return m }

// TransactionsReqValidationError is the validation error returned by
// TransactionsReq.Validate if the designated constraints aren't met.
type TransactionsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransactionsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransactionsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransactionsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransactionsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransactionsReqValidationError) ErrorName() string { return "TransactionsReqValidationError" }

// Error satisfies the builtin error interface
func (e TransactionsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransactionsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransactionsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransactionsReqValidationError{}

// Validate checks the field values on TransactionsRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TransactionsRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransactionsRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransactionsRspMultiError, or nil if none found.
func (m *TransactionsRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *TransactionsRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BillId

	// no validation rules for PrepayId

	if len(errors) > 0 {
		return TransactionsRspMultiError(errors)
	}

	return nil
}

// TransactionsRspMultiError is an error wrapping multiple validation errors
// returned by TransactionsRsp.ValidateAll() if the designated constraints
// aren't met.
type TransactionsRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransactionsRspMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransactionsRspMultiError) AllErrors() []error { return m }

// TransactionsRspValidationError is the validation error returned by
// TransactionsRsp.Validate if the designated constraints aren't met.
type TransactionsRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransactionsRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransactionsRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransactionsRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransactionsRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransactionsRspValidationError) ErrorName() string { return "TransactionsRspValidationError" }

// Error satisfies the builtin error interface
func (e TransactionsRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransactionsRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransactionsRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransactionsRspValidationError{}

// Validate checks the field values on PayCallbackReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PayCallbackReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PayCallbackReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PayCallbackReqMultiError,
// or nil if none found.
func (m *PayCallbackReq) ValidateAll() error {
	return m.validate(true)
}

func (m *PayCallbackReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for CreateTime

	// no validation rules for ResourceType

	// no validation rules for EventType

	// no validation rules for Summary

	if len(errors) > 0 {
		return PayCallbackReqMultiError(errors)
	}

	return nil
}

// PayCallbackReqMultiError is an error wrapping multiple validation errors
// returned by PayCallbackReq.ValidateAll() if the designated constraints
// aren't met.
type PayCallbackReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PayCallbackReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PayCallbackReqMultiError) AllErrors() []error { return m }

// PayCallbackReqValidationError is the validation error returned by
// PayCallbackReq.Validate if the designated constraints aren't met.
type PayCallbackReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PayCallbackReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PayCallbackReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PayCallbackReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PayCallbackReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PayCallbackReqValidationError) ErrorName() string { return "PayCallbackReqValidationError" }

// Error satisfies the builtin error interface
func (e PayCallbackReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPayCallbackReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PayCallbackReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PayCallbackReqValidationError{}

// Validate checks the field values on PayCallbackRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PayCallbackRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PayCallbackRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PayCallbackRspMultiError,
// or nil if none found.
func (m *PayCallbackRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *PayCallbackRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return PayCallbackRspMultiError(errors)
	}

	return nil
}

// PayCallbackRspMultiError is an error wrapping multiple validation errors
// returned by PayCallbackRsp.ValidateAll() if the designated constraints
// aren't met.
type PayCallbackRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PayCallbackRspMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PayCallbackRspMultiError) AllErrors() []error { return m }

// PayCallbackRspValidationError is the validation error returned by
// PayCallbackRsp.Validate if the designated constraints aren't met.
type PayCallbackRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PayCallbackRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PayCallbackRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PayCallbackRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PayCallbackRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PayCallbackRspValidationError) ErrorName() string { return "PayCallbackRspValidationError" }

// Error satisfies the builtin error interface
func (e PayCallbackRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPayCallbackRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PayCallbackRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PayCallbackRspValidationError{}
