// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wxpay.proto

package wxpay

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TransactionsReq_VipType int32

const (
	TransactionsReq_Unkown  TransactionsReq_VipType = 0
	TransactionsReq_Hour    TransactionsReq_VipType = 1
	TransactionsReq_Day     TransactionsReq_VipType = 2
	TransactionsReq_Week    TransactionsReq_VipType = 3
	TransactionsReq_Month   TransactionsReq_VipType = 4
	TransactionsReq_Quarter TransactionsReq_VipType = 5
	TransactionsReq_Year    TransactionsReq_VipType = 6
)

var TransactionsReq_VipType_name = map[int32]string{
	0: "Unkown",
	1: "Hour",
	2: "Day",
	3: "Week",
	4: "Month",
	5: "Quarter",
	6: "Year",
}

var TransactionsReq_VipType_value = map[string]int32{
	"Unkown":  0,
	"Hour":    1,
	"Day":     2,
	"Week":    3,
	"Month":   4,
	"Quarter": 5,
	"Year":    6,
}

func (x TransactionsReq_VipType) String() string {
	return proto.EnumName(TransactionsReq_VipType_name, int32(x))
}

func (TransactionsReq_VipType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{0, 0}
}

// 微信交易接口
type TransactionsReq struct {
	UserOpenid           string                  `protobuf:"bytes,1,opt,name=user_openid,json=userOpenid,proto3" json:"user_openid,omitempty"`
	VipType              TransactionsReq_VipType `protobuf:"varint,2,opt,name=vip_type,json=vipType,proto3,enum=wxpay.TransactionsReq_VipType" json:"vip_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TransactionsReq) Reset()         { *m = TransactionsReq{} }
func (m *TransactionsReq) String() string { return proto.CompactTextString(m) }
func (*TransactionsReq) ProtoMessage()    {}
func (*TransactionsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{0}
}
func (m *TransactionsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsReq.Unmarshal(m, b)
}
func (m *TransactionsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsReq.Marshal(b, m, deterministic)
}
func (m *TransactionsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsReq.Merge(m, src)
}
func (m *TransactionsReq) XXX_Size() int {
	return xxx_messageInfo_TransactionsReq.Size(m)
}
func (m *TransactionsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsReq.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsReq proto.InternalMessageInfo

func (m *TransactionsReq) GetUserOpenid() string {
	if m != nil {
		return m.UserOpenid
	}
	return ""
}

func (m *TransactionsReq) GetVipType() TransactionsReq_VipType {
	if m != nil {
		return m.VipType
	}
	return TransactionsReq_Unkown
}

type TransactionsRsp struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce                string   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Package              string   `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`
	SignType             string   `protobuf:"bytes,5,opt,name=sign_type,json=signType,proto3" json:"sign_type,omitempty"`
	PaySign              string   `protobuf:"bytes,6,opt,name=pay_sign,json=paySign,proto3" json:"pay_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionsRsp) Reset()         { *m = TransactionsRsp{} }
func (m *TransactionsRsp) String() string { return proto.CompactTextString(m) }
func (*TransactionsRsp) ProtoMessage()    {}
func (*TransactionsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{1}
}
func (m *TransactionsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsRsp.Unmarshal(m, b)
}
func (m *TransactionsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsRsp.Marshal(b, m, deterministic)
}
func (m *TransactionsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsRsp.Merge(m, src)
}
func (m *TransactionsRsp) XXX_Size() int {
	return xxx_messageInfo_TransactionsRsp.Size(m)
}
func (m *TransactionsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsRsp proto.InternalMessageInfo

func (m *TransactionsRsp) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *TransactionsRsp) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *TransactionsRsp) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *TransactionsRsp) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *TransactionsRsp) GetSignType() string {
	if m != nil {
		return m.SignType
	}
	return ""
}

func (m *TransactionsRsp) GetPaySign() string {
	if m != nil {
		return m.PaySign
	}
	return ""
}

// 交易结果回调接口
type PayCallbackReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayCallbackReq) Reset()         { *m = PayCallbackReq{} }
func (m *PayCallbackReq) String() string { return proto.CompactTextString(m) }
func (*PayCallbackReq) ProtoMessage()    {}
func (*PayCallbackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{2}
}
func (m *PayCallbackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayCallbackReq.Unmarshal(m, b)
}
func (m *PayCallbackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayCallbackReq.Marshal(b, m, deterministic)
}
func (m *PayCallbackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayCallbackReq.Merge(m, src)
}
func (m *PayCallbackReq) XXX_Size() int {
	return xxx_messageInfo_PayCallbackReq.Size(m)
}
func (m *PayCallbackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayCallbackReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayCallbackReq proto.InternalMessageInfo

type PayCallbackRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayCallbackRsp) Reset()         { *m = PayCallbackRsp{} }
func (m *PayCallbackRsp) String() string { return proto.CompactTextString(m) }
func (*PayCallbackRsp) ProtoMessage()    {}
func (*PayCallbackRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{3}
}
func (m *PayCallbackRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayCallbackRsp.Unmarshal(m, b)
}
func (m *PayCallbackRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayCallbackRsp.Marshal(b, m, deterministic)
}
func (m *PayCallbackRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayCallbackRsp.Merge(m, src)
}
func (m *PayCallbackRsp) XXX_Size() int {
	return xxx_messageInfo_PayCallbackRsp.Size(m)
}
func (m *PayCallbackRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayCallbackRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PayCallbackRsp proto.InternalMessageInfo

func (m *PayCallbackRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PayCallbackRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 获取用户openid接口
type GetUserOpenidReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserOpenidReq) Reset()         { *m = GetUserOpenidReq{} }
func (m *GetUserOpenidReq) String() string { return proto.CompactTextString(m) }
func (*GetUserOpenidReq) ProtoMessage()    {}
func (*GetUserOpenidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{4}
}
func (m *GetUserOpenidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserOpenidReq.Unmarshal(m, b)
}
func (m *GetUserOpenidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserOpenidReq.Marshal(b, m, deterministic)
}
func (m *GetUserOpenidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserOpenidReq.Merge(m, src)
}
func (m *GetUserOpenidReq) XXX_Size() int {
	return xxx_messageInfo_GetUserOpenidReq.Size(m)
}
func (m *GetUserOpenidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserOpenidReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserOpenidReq proto.InternalMessageInfo

func (m *GetUserOpenidReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type GetUserOpenidRsp struct {
	Openid               string   `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserOpenidRsp) Reset()         { *m = GetUserOpenidRsp{} }
func (m *GetUserOpenidRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserOpenidRsp) ProtoMessage()    {}
func (*GetUserOpenidRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{5}
}
func (m *GetUserOpenidRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserOpenidRsp.Unmarshal(m, b)
}
func (m *GetUserOpenidRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserOpenidRsp.Marshal(b, m, deterministic)
}
func (m *GetUserOpenidRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserOpenidRsp.Merge(m, src)
}
func (m *GetUserOpenidRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserOpenidRsp.Size(m)
}
func (m *GetUserOpenidRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserOpenidRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserOpenidRsp proto.InternalMessageInfo

func (m *GetUserOpenidRsp) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

// 获取用户vip信息接口
type GetUserVipReq struct {
	UserOpenid           string   `protobuf:"bytes,1,opt,name=user_openid,json=userOpenid,proto3" json:"user_openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserVipReq) Reset()         { *m = GetUserVipReq{} }
func (m *GetUserVipReq) String() string { return proto.CompactTextString(m) }
func (*GetUserVipReq) ProtoMessage()    {}
func (*GetUserVipReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{6}
}
func (m *GetUserVipReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserVipReq.Unmarshal(m, b)
}
func (m *GetUserVipReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserVipReq.Marshal(b, m, deterministic)
}
func (m *GetUserVipReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserVipReq.Merge(m, src)
}
func (m *GetUserVipReq) XXX_Size() int {
	return xxx_messageInfo_GetUserVipReq.Size(m)
}
func (m *GetUserVipReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserVipReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserVipReq proto.InternalMessageInfo

func (m *GetUserVipReq) GetUserOpenid() string {
	if m != nil {
		return m.UserOpenid
	}
	return ""
}

type GetUserVipRsp struct {
	ExpireTs             int64    `protobuf:"varint,1,opt,name=expire_ts,json=expireTs,proto3" json:"expire_ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserVipRsp) Reset()         { *m = GetUserVipRsp{} }
func (m *GetUserVipRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserVipRsp) ProtoMessage()    {}
func (*GetUserVipRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{7}
}
func (m *GetUserVipRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserVipRsp.Unmarshal(m, b)
}
func (m *GetUserVipRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserVipRsp.Marshal(b, m, deterministic)
}
func (m *GetUserVipRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserVipRsp.Merge(m, src)
}
func (m *GetUserVipRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserVipRsp.Size(m)
}
func (m *GetUserVipRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserVipRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserVipRsp proto.InternalMessageInfo

func (m *GetUserVipRsp) GetExpireTs() int64 {
	if m != nil {
		return m.ExpireTs
	}
	return 0
}

// *************************其他接口协议****************************
type GetAccessTokenRsp struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn            int64    `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Openid               string   `protobuf:"bytes,4,opt,name=openid,proto3" json:"openid,omitempty"`
	Scope                string   `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Unionid              string   `protobuf:"bytes,6,opt,name=unionid,proto3" json:"unionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRsp) Reset()         { *m = GetAccessTokenRsp{} }
func (m *GetAccessTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRsp) ProtoMessage()    {}
func (*GetAccessTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{8}
}
func (m *GetAccessTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRsp.Unmarshal(m, b)
}
func (m *GetAccessTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRsp.Merge(m, src)
}
func (m *GetAccessTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRsp.Size(m)
}
func (m *GetAccessTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRsp proto.InternalMessageInfo

func (m *GetAccessTokenRsp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAccessTokenRsp) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *GetAccessTokenRsp) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *GetAccessTokenRsp) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *GetAccessTokenRsp) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *GetAccessTokenRsp) GetUnionid() string {
	if m != nil {
		return m.Unionid
	}
	return ""
}

func init() {
	proto.RegisterEnum("wxpay.TransactionsReq_VipType", TransactionsReq_VipType_name, TransactionsReq_VipType_value)
	proto.RegisterType((*TransactionsReq)(nil), "wxpay.TransactionsReq")
	proto.RegisterType((*TransactionsRsp)(nil), "wxpay.TransactionsRsp")
	proto.RegisterType((*PayCallbackReq)(nil), "wxpay.PayCallbackReq")
	proto.RegisterType((*PayCallbackRsp)(nil), "wxpay.PayCallbackRsp")
	proto.RegisterType((*GetUserOpenidReq)(nil), "wxpay.GetUserOpenidReq")
	proto.RegisterType((*GetUserOpenidRsp)(nil), "wxpay.GetUserOpenidRsp")
	proto.RegisterType((*GetUserVipReq)(nil), "wxpay.GetUserVipReq")
	proto.RegisterType((*GetUserVipRsp)(nil), "wxpay.GetUserVipRsp")
	proto.RegisterType((*GetAccessTokenRsp)(nil), "wxpay.GetAccessTokenRsp")
}

func init() { proto.RegisterFile("wxpay.proto", fileDescriptor_f807639548d25710) }

var fileDescriptor_f807639548d25710 = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xe3, 0x36,
	0x10, 0xae, 0xfc, 0xef, 0xb1, 0x93, 0xa8, 0x44, 0x9a, 0xa8, 0x4e, 0x5a, 0xa4, 0xea, 0xc5, 0x30,
	0x5a, 0x0b, 0x48, 0x51, 0xa0, 0xcd, 0xa1, 0x40, 0xdd, 0x02, 0x69, 0x0f, 0x41, 0x53, 0xc5, 0x49,
	0xd0, 0x5e, 0x04, 0x46, 0x66, 0x65, 0xd6, 0x36, 0xc9, 0x88, 0x94, 0x63, 0x61, 0x6f, 0x79, 0x85,
	0x7d, 0x8e, 0x7d, 0x89, 0x7d, 0x85, 0x7d, 0x81, 0x3d, 0x2c, 0xf6, 0x21, 0x72, 0x5a, 0x90, 0x92,
	0x7f, 0x61, 0x2c, 0xb2, 0x27, 0xcf, 0x7c, 0x33, 0xf3, 0xcd, 0x0c, 0xe7, 0xb3, 0xa0, 0xf1, 0x30,
	0x13, 0x38, 0xed, 0x8a, 0x98, 0x2b, 0x8e, 0xca, 0xc6, 0x69, 0x1d, 0x47, 0x9c, 0x47, 0x63, 0xe2,
	0x61, 0x41, 0x3d, 0xcc, 0x18, 0x57, 0x58, 0x51, 0xce, 0x64, 0x96, 0xd4, 0x3a, 0x9c, 0xe2, 0x31,
	0x1d, 0x60, 0x45, 0xbc, 0xb9, 0x91, 0x07, 0xf6, 0x23, 0x1e, 0x71, 0x63, 0x7a, 0xda, 0xca, 0x50,
	0xf7, 0xad, 0x05, 0x7b, 0xfd, 0x18, 0x33, 0x89, 0x43, 0xc3, 0xe2, 0x93, 0x7b, 0xd4, 0x86, 0x46,
	0x22, 0x49, 0x1c, 0x70, 0x41, 0x18, 0x1d, 0x38, 0xd6, 0x89, 0xd5, 0xae, 0xf7, 0xaa, 0x4f, 0xbd,
	0x52, 0x5c, 0xb0, 0x2d, 0x1f, 0x74, 0xec, 0x2f, 0x13, 0x42, 0x17, 0x50, 0x9b, 0x52, 0x11, 0xa8,
	0x54, 0x10, 0xa7, 0x70, 0x62, 0xb5, 0x77, 0x4f, 0xbf, 0xee, 0x66, 0x13, 0x6f, 0x70, 0x76, 0x6f,
	0xa8, 0xe8, 0xa7, 0x82, 0xf4, 0xd0, 0x53, 0x6f, 0xef, 0xd1, 0x6a, 0x3a, 0x96, 0x53, 0x70, 0x8a,
	0x4e, 0xc9, 0x29, 0x3b, 0x15, 0xbf, 0x3a, 0xcd, 0x82, 0x6e, 0x1f, 0xaa, 0x79, 0x1e, 0x02, 0xa8,
	0x5c, 0xb3, 0x11, 0x7f, 0x60, 0xf6, 0x67, 0xa8, 0x06, 0xa5, 0x3f, 0x78, 0x12, 0xdb, 0x16, 0xaa,
	0x42, 0xf1, 0x77, 0x9c, 0xda, 0x05, 0x0d, 0xdd, 0x12, 0x32, 0xb2, 0x8b, 0xa8, 0x0e, 0xe5, 0x0b,
	0xce, 0xd4, 0xd0, 0x2e, 0xa1, 0x06, 0x54, 0xff, 0x4e, 0x70, 0xac, 0x48, 0x6c, 0x97, 0x75, 0xc6,
	0x3f, 0x04, 0xc7, 0x76, 0xc5, 0x7d, 0xb5, 0xb9, 0xa2, 0x14, 0x68, 0x1f, 0xca, 0x58, 0x88, 0xf9,
	0x72, 0x7e, 0xe6, 0xa0, 0x63, 0xa8, 0x2b, 0x3a, 0x21, 0x52, 0xe1, 0x89, 0x30, 0xfb, 0xd4, 0xfd,
	0x25, 0xa0, 0x6b, 0x18, 0x67, 0x21, 0x71, 0x8a, 0x59, 0x8d, 0x71, 0x90, 0x03, 0x55, 0x81, 0xc3,
	0x11, 0x8e, 0x88, 0x53, 0x32, 0xf8, 0xdc, 0x45, 0x47, 0x50, 0x97, 0x34, 0x62, 0xd9, 0xeb, 0x94,
	0x4d, 0xac, 0xa6, 0x01, 0xb3, 0xdf, 0x97, 0x50, 0x13, 0x38, 0x0d, 0xb4, 0xef, 0x54, 0xe6, 0x75,
	0xe9, 0x15, 0x8d, 0x98, 0x6b, 0xc3, 0xee, 0x25, 0x4e, 0x7f, 0xc3, 0xe3, 0xf1, 0x1d, 0x0e, 0x47,
	0x3e, 0xb9, 0x77, 0x7f, 0x59, 0x47, 0xa4, 0x40, 0x08, 0x4a, 0x21, 0x1f, 0x90, 0x7c, 0x7c, 0x63,
	0xeb, 0x49, 0x26, 0x44, 0x4a, 0x3d, 0x49, 0x36, 0xfb, 0xdc, 0x75, 0x3d, 0xb0, 0xcf, 0x89, 0xba,
	0x5e, 0xdc, 0x4d, 0x1f, 0xf9, 0x68, 0x95, 0x61, 0x79, 0x5d, 0x03, 0xba, 0x9d, 0xcd, 0x02, 0x29,
	0xd0, 0x01, 0x54, 0x56, 0x05, 0xe1, 0xe7, 0x9e, 0xfb, 0x33, 0xec, 0xe4, 0xb9, 0x37, 0x54, 0x7c,
	0x92, 0x7c, 0xdc, 0xef, 0xd6, 0x4a, 0xa5, 0xd0, 0x4f, 0x46, 0x66, 0x82, 0xc6, 0x24, 0x50, 0xd2,
	0x14, 0x16, 0xfd, 0x5a, 0x06, 0xf4, 0xa5, 0xfb, 0xda, 0x82, 0xcf, 0xcf, 0x89, 0xfa, 0x35, 0x0c,
	0x89, 0x94, 0x7d, 0x3e, 0x22, 0x4c, 0x97, 0x7c, 0x03, 0x4d, 0x6c, 0x90, 0x40, 0x69, 0x28, 0x1f,
	0xae, 0x81, 0x97, 0x59, 0xe8, 0x2b, 0x80, 0x8c, 0x44, 0x06, 0x94, 0x99, 0xb7, 0x29, 0xfa, 0x79,
	0x1f, 0xf9, 0x27, 0x43, 0xdf, 0xc2, 0x4e, 0x4c, 0xfe, 0x8b, 0x89, 0x1c, 0xe6, 0x14, 0xd9, 0x7d,
	0x9b, 0x39, 0x98, 0x71, 0x2c, 0xb7, 0x2f, 0xad, 0x6e, 0xaf, 0x45, 0x21, 0x43, 0xbe, 0x38, 0x70,
	0xe6, 0xe8, 0x53, 0x24, 0x8c, 0x72, 0x9d, 0x9e, 0x1f, 0x37, 0x77, 0x4f, 0xdf, 0x17, 0xa1, 0x71,
	0x4b, 0x66, 0x94, 0x5d, 0xe2, 0xf4, 0x6a, 0x1a, 0xa3, 0x04, 0x9a, 0xab, 0xda, 0x44, 0x07, 0xdb,
	0xff, 0x3f, 0xad, 0xad, 0xb8, 0x14, 0xee, 0x8f, 0x8f, 0x6f, 0xde, 0xbd, 0x2c, 0x78, 0x6e, 0xc7,
	0x93, 0xc3, 0x64, 0xc0, 0x59, 0xe4, 0x99, 0x3c, 0xef, 0x81, 0xd0, 0x19, 0x65, 0x81, 0xd1, 0xd8,
	0x34, 0xf6, 0xd4, 0x4a, 0xd9, 0x99, 0xd5, 0x41, 0x31, 0x34, 0x56, 0x14, 0x85, 0xbe, 0xc8, 0xd9,
	0xd7, 0x75, 0xd7, 0xda, 0x06, 0x3f, 0xbf, 0xa7, 0xfe, 0x0d, 0xf3, 0x32, 0xdd, 0xf3, 0xc5, 0xe2,
	0xda, 0xf9, 0xd7, 0xe3, 0x30, 0xa7, 0xdf, 0xd4, 0x66, 0x6b, 0x7b, 0x40, 0x0a, 0xf7, 0x27, 0xd3,
	0xf9, 0xd4, 0xfd, 0xfe, 0xe3, 0x9d, 0x23, 0xa2, 0x82, 0x15, 0x09, 0xea, 0xe6, 0x1c, 0x60, 0x29,
	0x35, 0xb4, 0xbf, 0xde, 0x20, 0x13, 0x6e, 0x6b, 0x0b, 0xfa, 0xfc, 0x6d, 0x17, 0x3d, 0xa7, 0x54,
	0x9c, 0x59, 0x9d, 0x5e, 0xe7, 0xdf, 0x76, 0x44, 0xd5, 0x30, 0xb9, 0xeb, 0x86, 0x7c, 0xe2, 0xfd,
	0x4f, 0x98, 0x24, 0x2c, 0x4a, 0xb8, 0x97, 0x7d, 0x81, 0xd7, 0xa8, 0xee, 0x2a, 0x06, 0xfc, 0xe1,
	0x43, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x2b, 0x78, 0xf6, 0xee, 0x05, 0x00, 0x00,
}
