// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wxpay.proto

package wxpay

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TransactionsReq_VipType int32

const (
	TransactionsReq_Unknown TransactionsReq_VipType = 0
	TransactionsReq_Hour    TransactionsReq_VipType = 1
	TransactionsReq_Day     TransactionsReq_VipType = 2
	TransactionsReq_Week    TransactionsReq_VipType = 3
	TransactionsReq_Month   TransactionsReq_VipType = 4
)

var TransactionsReq_VipType_name = map[int32]string{
	0: "Unknown",
	1: "Hour",
	2: "Day",
	3: "Week",
	4: "Month",
}

var TransactionsReq_VipType_value = map[string]int32{
	"Unknown": 0,
	"Hour":    1,
	"Day":     2,
	"Week":    3,
	"Month":   4,
}

func (x TransactionsReq_VipType) String() string {
	return proto.EnumName(TransactionsReq_VipType_name, int32(x))
}

func (TransactionsReq_VipType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{0, 0}
}

// 微信交易接口
type TransactionsReq struct {
	UserOpenId           string                  `protobuf:"bytes,1,opt,name=user_open_id,json=userOpenId,proto3" json:"user_open_id,omitempty"`
	VipType              TransactionsReq_VipType `protobuf:"varint,2,opt,name=vip_type,json=vipType,proto3,enum=wxpay.TransactionsReq_VipType" json:"vip_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TransactionsReq) Reset()         { *m = TransactionsReq{} }
func (m *TransactionsReq) String() string { return proto.CompactTextString(m) }
func (*TransactionsReq) ProtoMessage()    {}
func (*TransactionsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{0}
}
func (m *TransactionsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsReq.Unmarshal(m, b)
}
func (m *TransactionsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsReq.Marshal(b, m, deterministic)
}
func (m *TransactionsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsReq.Merge(m, src)
}
func (m *TransactionsReq) XXX_Size() int {
	return xxx_messageInfo_TransactionsReq.Size(m)
}
func (m *TransactionsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsReq.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsReq proto.InternalMessageInfo

func (m *TransactionsReq) GetUserOpenId() string {
	if m != nil {
		return m.UserOpenId
	}
	return ""
}

func (m *TransactionsReq) GetVipType() TransactionsReq_VipType {
	if m != nil {
		return m.VipType
	}
	return TransactionsReq_Unknown
}

type TransactionsRsp struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	PrepayId             string   `protobuf:"bytes,2,opt,name=prepay_id,json=prepayId,proto3" json:"prepay_id,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce                string   `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Package              string   `protobuf:"bytes,5,opt,name=package,proto3" json:"package,omitempty"`
	SignType             string   `protobuf:"bytes,6,opt,name=sign_type,json=signType,proto3" json:"sign_type,omitempty"`
	PaySign              string   `protobuf:"bytes,7,opt,name=pay_sign,json=paySign,proto3" json:"pay_sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionsRsp) Reset()         { *m = TransactionsRsp{} }
func (m *TransactionsRsp) String() string { return proto.CompactTextString(m) }
func (*TransactionsRsp) ProtoMessage()    {}
func (*TransactionsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{1}
}
func (m *TransactionsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionsRsp.Unmarshal(m, b)
}
func (m *TransactionsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionsRsp.Marshal(b, m, deterministic)
}
func (m *TransactionsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionsRsp.Merge(m, src)
}
func (m *TransactionsRsp) XXX_Size() int {
	return xxx_messageInfo_TransactionsRsp.Size(m)
}
func (m *TransactionsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionsRsp proto.InternalMessageInfo

func (m *TransactionsRsp) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *TransactionsRsp) GetPrepayId() string {
	if m != nil {
		return m.PrepayId
	}
	return ""
}

func (m *TransactionsRsp) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *TransactionsRsp) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *TransactionsRsp) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *TransactionsRsp) GetSignType() string {
	if m != nil {
		return m.SignType
	}
	return ""
}

func (m *TransactionsRsp) GetPaySign() string {
	if m != nil {
		return m.PaySign
	}
	return ""
}

// 交易结果回调接口
type PayCallbackReq struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateTime           string                   `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ResourceType         string                   `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	EventType            string                   `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Summary              string                   `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Resource             *PayCallbackReq_Resource `protobuf:"bytes,6,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PayCallbackReq) Reset()         { *m = PayCallbackReq{} }
func (m *PayCallbackReq) String() string { return proto.CompactTextString(m) }
func (*PayCallbackReq) ProtoMessage()    {}
func (*PayCallbackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{2}
}
func (m *PayCallbackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayCallbackReq.Unmarshal(m, b)
}
func (m *PayCallbackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayCallbackReq.Marshal(b, m, deterministic)
}
func (m *PayCallbackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayCallbackReq.Merge(m, src)
}
func (m *PayCallbackReq) XXX_Size() int {
	return xxx_messageInfo_PayCallbackReq.Size(m)
}
func (m *PayCallbackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayCallbackReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayCallbackReq proto.InternalMessageInfo

func (m *PayCallbackReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PayCallbackReq) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *PayCallbackReq) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *PayCallbackReq) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *PayCallbackReq) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *PayCallbackReq) GetResource() *PayCallbackReq_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type PayCallbackReq_Resource struct {
	OriginalType         string   `protobuf:"bytes,1,opt,name=original_type,json=originalType,proto3" json:"original_type,omitempty"`
	Algorithm            string   `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Ciphertext           string   `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	AssociatedData       string   `protobuf:"bytes,4,opt,name=associated_data,json=associatedData,proto3" json:"associated_data,omitempty"`
	Nonce                string   `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayCallbackReq_Resource) Reset()         { *m = PayCallbackReq_Resource{} }
func (m *PayCallbackReq_Resource) String() string { return proto.CompactTextString(m) }
func (*PayCallbackReq_Resource) ProtoMessage()    {}
func (*PayCallbackReq_Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{2, 0}
}
func (m *PayCallbackReq_Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayCallbackReq_Resource.Unmarshal(m, b)
}
func (m *PayCallbackReq_Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayCallbackReq_Resource.Marshal(b, m, deterministic)
}
func (m *PayCallbackReq_Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayCallbackReq_Resource.Merge(m, src)
}
func (m *PayCallbackReq_Resource) XXX_Size() int {
	return xxx_messageInfo_PayCallbackReq_Resource.Size(m)
}
func (m *PayCallbackReq_Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_PayCallbackReq_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_PayCallbackReq_Resource proto.InternalMessageInfo

func (m *PayCallbackReq_Resource) GetOriginalType() string {
	if m != nil {
		return m.OriginalType
	}
	return ""
}

func (m *PayCallbackReq_Resource) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *PayCallbackReq_Resource) GetCiphertext() string {
	if m != nil {
		return m.Ciphertext
	}
	return ""
}

func (m *PayCallbackReq_Resource) GetAssociatedData() string {
	if m != nil {
		return m.AssociatedData
	}
	return ""
}

func (m *PayCallbackReq_Resource) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

type PayCallbackRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayCallbackRsp) Reset()         { *m = PayCallbackRsp{} }
func (m *PayCallbackRsp) String() string { return proto.CompactTextString(m) }
func (*PayCallbackRsp) ProtoMessage()    {}
func (*PayCallbackRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{3}
}
func (m *PayCallbackRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayCallbackRsp.Unmarshal(m, b)
}
func (m *PayCallbackRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayCallbackRsp.Marshal(b, m, deterministic)
}
func (m *PayCallbackRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayCallbackRsp.Merge(m, src)
}
func (m *PayCallbackRsp) XXX_Size() int {
	return xxx_messageInfo_PayCallbackRsp.Size(m)
}
func (m *PayCallbackRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayCallbackRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PayCallbackRsp proto.InternalMessageInfo

func (m *PayCallbackRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PayCallbackRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 获取用户openid接口
type GetUserOpenidReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserOpenidReq) Reset()         { *m = GetUserOpenidReq{} }
func (m *GetUserOpenidReq) String() string { return proto.CompactTextString(m) }
func (*GetUserOpenidReq) ProtoMessage()    {}
func (*GetUserOpenidReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{4}
}
func (m *GetUserOpenidReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserOpenidReq.Unmarshal(m, b)
}
func (m *GetUserOpenidReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserOpenidReq.Marshal(b, m, deterministic)
}
func (m *GetUserOpenidReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserOpenidReq.Merge(m, src)
}
func (m *GetUserOpenidReq) XXX_Size() int {
	return xxx_messageInfo_GetUserOpenidReq.Size(m)
}
func (m *GetUserOpenidReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserOpenidReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserOpenidReq proto.InternalMessageInfo

func (m *GetUserOpenidReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type GetUserOpenidRsp struct {
	Openid               string   `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserOpenidRsp) Reset()         { *m = GetUserOpenidRsp{} }
func (m *GetUserOpenidRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserOpenidRsp) ProtoMessage()    {}
func (*GetUserOpenidRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{5}
}
func (m *GetUserOpenidRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserOpenidRsp.Unmarshal(m, b)
}
func (m *GetUserOpenidRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserOpenidRsp.Marshal(b, m, deterministic)
}
func (m *GetUserOpenidRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserOpenidRsp.Merge(m, src)
}
func (m *GetUserOpenidRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserOpenidRsp.Size(m)
}
func (m *GetUserOpenidRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserOpenidRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserOpenidRsp proto.InternalMessageInfo

func (m *GetUserOpenidRsp) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

// *************************其他接口协议****************************
type GetAccessTokenRsp struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn            int64    `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Openid               string   `protobuf:"bytes,4,opt,name=openid,proto3" json:"openid,omitempty"`
	Scope                string   `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Unionid              string   `protobuf:"bytes,6,opt,name=unionid,proto3" json:"unionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRsp) Reset()         { *m = GetAccessTokenRsp{} }
func (m *GetAccessTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRsp) ProtoMessage()    {}
func (*GetAccessTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{6}
}
func (m *GetAccessTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRsp.Unmarshal(m, b)
}
func (m *GetAccessTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRsp.Merge(m, src)
}
func (m *GetAccessTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRsp.Size(m)
}
func (m *GetAccessTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRsp proto.InternalMessageInfo

func (m *GetAccessTokenRsp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAccessTokenRsp) GetExpiresIn() int64 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *GetAccessTokenRsp) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *GetAccessTokenRsp) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *GetAccessTokenRsp) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *GetAccessTokenRsp) GetUnionid() string {
	if m != nil {
		return m.Unionid
	}
	return ""
}

type WxTransactionsReq struct {
	Mchid                string                    `protobuf:"bytes,1,opt,name=mchid,proto3" json:"mchid,omitempty"`
	OutTradeNo           string                    `protobuf:"bytes,2,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	Appid                string                    `protobuf:"bytes,3,opt,name=appid,proto3" json:"appid,omitempty"`
	Description          string                    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	NotifyUrl            string                    `protobuf:"bytes,5,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	Amount               *WxTransactionsReq_Amount `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Payer                *WxTransactionsReq_Payer  `protobuf:"bytes,7,opt,name=payer,proto3" json:"payer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *WxTransactionsReq) Reset()         { *m = WxTransactionsReq{} }
func (m *WxTransactionsReq) String() string { return proto.CompactTextString(m) }
func (*WxTransactionsReq) ProtoMessage()    {}
func (*WxTransactionsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{7}
}
func (m *WxTransactionsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxTransactionsReq.Unmarshal(m, b)
}
func (m *WxTransactionsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxTransactionsReq.Marshal(b, m, deterministic)
}
func (m *WxTransactionsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxTransactionsReq.Merge(m, src)
}
func (m *WxTransactionsReq) XXX_Size() int {
	return xxx_messageInfo_WxTransactionsReq.Size(m)
}
func (m *WxTransactionsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WxTransactionsReq.DiscardUnknown(m)
}

var xxx_messageInfo_WxTransactionsReq proto.InternalMessageInfo

func (m *WxTransactionsReq) GetMchid() string {
	if m != nil {
		return m.Mchid
	}
	return ""
}

func (m *WxTransactionsReq) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

func (m *WxTransactionsReq) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *WxTransactionsReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *WxTransactionsReq) GetNotifyUrl() string {
	if m != nil {
		return m.NotifyUrl
	}
	return ""
}

func (m *WxTransactionsReq) GetAmount() *WxTransactionsReq_Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *WxTransactionsReq) GetPayer() *WxTransactionsReq_Payer {
	if m != nil {
		return m.Payer
	}
	return nil
}

type WxTransactionsReq_Amount struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxTransactionsReq_Amount) Reset()         { *m = WxTransactionsReq_Amount{} }
func (m *WxTransactionsReq_Amount) String() string { return proto.CompactTextString(m) }
func (*WxTransactionsReq_Amount) ProtoMessage()    {}
func (*WxTransactionsReq_Amount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{7, 0}
}
func (m *WxTransactionsReq_Amount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxTransactionsReq_Amount.Unmarshal(m, b)
}
func (m *WxTransactionsReq_Amount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxTransactionsReq_Amount.Marshal(b, m, deterministic)
}
func (m *WxTransactionsReq_Amount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxTransactionsReq_Amount.Merge(m, src)
}
func (m *WxTransactionsReq_Amount) XXX_Size() int {
	return xxx_messageInfo_WxTransactionsReq_Amount.Size(m)
}
func (m *WxTransactionsReq_Amount) XXX_DiscardUnknown() {
	xxx_messageInfo_WxTransactionsReq_Amount.DiscardUnknown(m)
}

var xxx_messageInfo_WxTransactionsReq_Amount proto.InternalMessageInfo

func (m *WxTransactionsReq_Amount) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *WxTransactionsReq_Amount) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type WxTransactionsReq_Payer struct {
	Openid               string   `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxTransactionsReq_Payer) Reset()         { *m = WxTransactionsReq_Payer{} }
func (m *WxTransactionsReq_Payer) String() string { return proto.CompactTextString(m) }
func (*WxTransactionsReq_Payer) ProtoMessage()    {}
func (*WxTransactionsReq_Payer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{7, 1}
}
func (m *WxTransactionsReq_Payer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxTransactionsReq_Payer.Unmarshal(m, b)
}
func (m *WxTransactionsReq_Payer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxTransactionsReq_Payer.Marshal(b, m, deterministic)
}
func (m *WxTransactionsReq_Payer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxTransactionsReq_Payer.Merge(m, src)
}
func (m *WxTransactionsReq_Payer) XXX_Size() int {
	return xxx_messageInfo_WxTransactionsReq_Payer.Size(m)
}
func (m *WxTransactionsReq_Payer) XXX_DiscardUnknown() {
	xxx_messageInfo_WxTransactionsReq_Payer.DiscardUnknown(m)
}

var xxx_messageInfo_WxTransactionsReq_Payer proto.InternalMessageInfo

func (m *WxTransactionsReq_Payer) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

type WxTransactionsRsp struct {
	PrepayId             string   `protobuf:"bytes,1,opt,name=prepay_id,json=prepayId,proto3" json:"prepay_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxTransactionsRsp) Reset()         { *m = WxTransactionsRsp{} }
func (m *WxTransactionsRsp) String() string { return proto.CompactTextString(m) }
func (*WxTransactionsRsp) ProtoMessage()    {}
func (*WxTransactionsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f807639548d25710, []int{8}
}
func (m *WxTransactionsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxTransactionsRsp.Unmarshal(m, b)
}
func (m *WxTransactionsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxTransactionsRsp.Marshal(b, m, deterministic)
}
func (m *WxTransactionsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxTransactionsRsp.Merge(m, src)
}
func (m *WxTransactionsRsp) XXX_Size() int {
	return xxx_messageInfo_WxTransactionsRsp.Size(m)
}
func (m *WxTransactionsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_WxTransactionsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_WxTransactionsRsp proto.InternalMessageInfo

func (m *WxTransactionsRsp) GetPrepayId() string {
	if m != nil {
		return m.PrepayId
	}
	return ""
}

func init() {
	proto.RegisterEnum("wxpay.TransactionsReq_VipType", TransactionsReq_VipType_name, TransactionsReq_VipType_value)
	proto.RegisterType((*TransactionsReq)(nil), "wxpay.TransactionsReq")
	proto.RegisterType((*TransactionsRsp)(nil), "wxpay.TransactionsRsp")
	proto.RegisterType((*PayCallbackReq)(nil), "wxpay.PayCallbackReq")
	proto.RegisterType((*PayCallbackReq_Resource)(nil), "wxpay.PayCallbackReq.Resource")
	proto.RegisterType((*PayCallbackRsp)(nil), "wxpay.PayCallbackRsp")
	proto.RegisterType((*GetUserOpenidReq)(nil), "wxpay.GetUserOpenidReq")
	proto.RegisterType((*GetUserOpenidRsp)(nil), "wxpay.GetUserOpenidRsp")
	proto.RegisterType((*GetAccessTokenRsp)(nil), "wxpay.GetAccessTokenRsp")
	proto.RegisterType((*WxTransactionsReq)(nil), "wxpay.WxTransactionsReq")
	proto.RegisterType((*WxTransactionsReq_Amount)(nil), "wxpay.WxTransactionsReq.Amount")
	proto.RegisterType((*WxTransactionsReq_Payer)(nil), "wxpay.WxTransactionsReq.Payer")
	proto.RegisterType((*WxTransactionsRsp)(nil), "wxpay.WxTransactionsRsp")
}

func init() { proto.RegisterFile("wxpay.proto", fileDescriptor_f807639548d25710) }

var fileDescriptor_f807639548d25710 = []byte{
	// 968 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4f, 0x6f, 0x23, 0x35,
	0x14, 0x67, 0x92, 0xa6, 0x49, 0x5e, 0xba, 0xdd, 0xac, 0x55, 0x76, 0x43, 0x28, 0xdb, 0x32, 0x48,
	0x50, 0x55, 0x22, 0x83, 0x0a, 0x08, 0xe8, 0x61, 0xa5, 0x85, 0x95, 0x96, 0x1e, 0x80, 0x2a, 0x9b,
	0x52, 0x89, 0xcb, 0xc8, 0x9d, 0xf1, 0x4e, 0x4c, 0x32, 0xb6, 0xb1, 0x3d, 0x69, 0x46, 0xdc, 0x38,
	0x72, 0xe5, 0x6b, 0x20, 0x3e, 0x04, 0x47, 0xae, 0x7c, 0x05, 0xce, 0xdc, 0xb8, 0x23, 0xff, 0x99,
	0xfc, 0x6b, 0x40, 0x7b, 0x1a, 0xbf, 0x9f, 0x7f, 0x7e, 0xef, 0xf7, 0x9e, 0xfd, 0xde, 0x40, 0xe7,
	0x76, 0x2e, 0x70, 0x39, 0x10, 0x92, 0x6b, 0x8e, 0x1a, 0xd6, 0xe8, 0x1f, 0x66, 0x9c, 0x67, 0x53,
	0x12, 0x61, 0x41, 0x23, 0xcc, 0x18, 0xd7, 0x58, 0x53, 0xce, 0x94, 0x23, 0xf5, 0x1f, 0xcd, 0xf0,
	0x94, 0xa6, 0x58, 0x93, 0xa8, 0x5a, 0xf8, 0x8d, 0x83, 0x8c, 0x67, 0xdc, 0x2e, 0x23, 0xb3, 0x72,
	0x68, 0xf8, 0x5b, 0x00, 0xf7, 0x47, 0x12, 0x33, 0x85, 0x13, 0xeb, 0x65, 0x48, 0x7e, 0x40, 0xc7,
	0xb0, 0x57, 0x28, 0x22, 0x63, 0x2e, 0x08, 0x8b, 0x69, 0xda, 0x0b, 0x8e, 0x83, 0x93, 0xf6, 0x10,
	0x0c, 0xf6, 0x8d, 0x20, 0xec, 0x22, 0x45, 0x9f, 0x41, 0x6b, 0x46, 0x45, 0xac, 0x4b, 0x41, 0x7a,
	0xb5, 0xe3, 0xe0, 0x64, 0xff, 0xec, 0xf1, 0xc0, 0x29, 0xdd, 0xf0, 0x35, 0xf8, 0x96, 0x8a, 0x51,
	0x29, 0xc8, 0xb0, 0x39, 0x73, 0x8b, 0xf0, 0x09, 0x34, 0x3d, 0x86, 0x3a, 0xd0, 0xbc, 0x62, 0x13,
	0xc6, 0x6f, 0x59, 0xf7, 0x35, 0xd4, 0x82, 0x9d, 0x2f, 0x79, 0x21, 0xbb, 0x01, 0x6a, 0x42, 0xfd,
	0x19, 0x2e, 0xbb, 0x35, 0x03, 0x5d, 0x13, 0x32, 0xe9, 0xd6, 0x51, 0x1b, 0x1a, 0x5f, 0x71, 0xa6,
	0xc7, 0xdd, 0x9d, 0xf0, 0x8f, 0x4d, 0xc1, 0x4a, 0xa0, 0x03, 0x68, 0x60, 0x21, 0x16, 0x4a, 0x9d,
	0x81, 0xde, 0x84, 0xb6, 0x90, 0x44, 0xe0, 0xd2, 0xe4, 0x50, 0xb3, 0x3b, 0x2d, 0x07, 0x5c, 0xa4,
	0xe8, 0x10, 0xda, 0x9a, 0xe6, 0x44, 0x69, 0x9c, 0x8b, 0x5e, 0xdd, 0x6e, 0x2e, 0x01, 0xe3, 0x90,
	0x71, 0x96, 0x90, 0xde, 0x8e, 0x73, 0x68, 0x0d, 0xd4, 0x83, 0xa6, 0xc0, 0xc9, 0x04, 0x67, 0xa4,
	0xd7, 0xb0, 0x78, 0x65, 0x9a, 0x50, 0x8a, 0x66, 0xcc, 0x15, 0x64, 0xd7, 0x85, 0x32, 0x80, 0x4d,
	0xf3, 0x0d, 0x68, 0x19, 0x11, 0xc6, 0xee, 0x35, 0xab, 0x73, 0xe5, 0x0b, 0x9a, 0xb1, 0xf0, 0xe7,
	0x3a, 0xec, 0x5f, 0xe2, 0xf2, 0x0b, 0x3c, 0x9d, 0xde, 0xe0, 0x64, 0x62, 0x8a, 0xbf, 0x0f, 0xb5,
	0x45, 0x22, 0x35, 0x9a, 0xa2, 0x23, 0xe8, 0x24, 0x92, 0x60, 0x4d, 0x62, 0x23, 0xcf, 0xe7, 0x01,
	0x0e, 0x1a, 0xd1, 0x9c, 0xa0, 0x77, 0xe0, 0x9e, 0x24, 0x8a, 0x17, 0x32, 0x21, 0x2e, 0xbe, 0xcb,
	0x66, 0xaf, 0x02, 0xad, 0x86, 0xb7, 0x00, 0xc8, 0x8c, 0x30, 0xed, 0x18, 0x2e, 0xab, 0xb6, 0x45,
	0xec, 0x76, 0x0f, 0x9a, 0xaa, 0xc8, 0x73, 0x2c, 0xcb, 0x2a, 0x33, 0x6f, 0xa2, 0x73, 0x68, 0x55,
	0x8e, 0x6c, 0x62, 0x9d, 0xc5, 0x4d, 0xaf, 0xeb, 0x1e, 0x0c, 0x3d, 0x6b, 0xb8, 0xe0, 0xf7, 0x7f,
	0x0d, 0xa0, 0x55, 0xc1, 0x46, 0x26, 0x97, 0x34, 0xa3, 0x0c, 0x4f, 0x9d, 0x08, 0x97, 0xe2, 0x5e,
	0x05, 0x5a, 0x1d, 0x87, 0xd0, 0xc6, 0xd3, 0x8c, 0x4b, 0xaa, 0xc7, 0xb9, 0x4f, 0x75, 0x09, 0xa0,
	0xc7, 0x00, 0x09, 0x15, 0x63, 0x22, 0x35, 0x99, 0x6b, 0x9f, 0xe6, 0x0a, 0x82, 0xde, 0x83, 0xfb,
	0x58, 0x29, 0x9e, 0x50, 0xac, 0x49, 0x1a, 0xa7, 0x58, 0x63, 0x9f, 0xe9, 0xfe, 0x12, 0x7e, 0x86,
	0x35, 0x5e, 0x5e, 0x6f, 0x63, 0xe5, 0x7a, 0xc3, 0x27, 0xeb, 0x77, 0xa1, 0x04, 0x42, 0xb0, 0x93,
	0xf0, 0xb4, 0x92, 0x6a, 0xd7, 0xa6, 0x54, 0x39, 0x51, 0xca, 0x3c, 0x02, 0x27, 0xb0, 0x32, 0xc3,
	0x77, 0xa1, 0xfb, 0x9c, 0xe8, 0x2b, 0xdf, 0x25, 0x34, 0x35, 0xb7, 0xb9, 0xc5, 0x43, 0x78, 0xba,
	0xc9, 0x53, 0x02, 0x3d, 0x84, 0x5d, 0x6e, 0x0d, 0xcf, 0xf4, 0x56, 0xf8, 0x7b, 0x00, 0x0f, 0x9e,
	0x13, 0xfd, 0x34, 0x49, 0x88, 0x52, 0x23, 0x3e, 0x21, 0xcc, 0xb0, 0xdf, 0x86, 0x3d, 0x6c, 0x91,
	0x58, 0x1b, 0xc8, 0x9f, 0xe9, 0xe0, 0x25, 0xcb, 0x5e, 0xf8, 0x5c, 0x50, 0x49, 0x54, 0x4c, 0x99,
	0x55, 0x5a, 0x1f, 0xb6, 0x3d, 0x72, 0xc1, 0xdc, 0xa3, 0x79, 0x29, 0x89, 0x1a, 0x7b, 0x17, 0x8b,
	0x47, 0x63, 0x41, 0xe7, 0x63, 0x29, 0x6a, 0x67, 0x55, 0x94, 0x29, 0x9f, 0x4a, 0xb8, 0x58, 0x94,
	0xcf, 0x1a, 0xa6, 0x30, 0x05, 0xa3, 0xdc, 0xd0, 0x5d, 0x07, 0x54, 0x66, 0xf8, 0x77, 0x0d, 0x1e,
	0x5c, 0xcf, 0x37, 0xa7, 0xcc, 0x01, 0x34, 0xf2, 0x64, 0xbc, 0x6c, 0x5a, 0x6b, 0x98, 0xd9, 0xc3,
	0x0b, 0x1d, 0x6b, 0x89, 0x53, 0x12, 0x33, 0x5e, 0xbd, 0x77, 0x5e, 0xe8, 0x91, 0x81, 0xbe, 0xe6,
	0xcb, 0x66, 0xaf, 0xaf, 0x36, 0xfb, 0x31, 0x74, 0x52, 0xa2, 0x12, 0x49, 0x85, 0x09, 0xe0, 0x05,
	0xaf, 0x42, 0xa6, 0x22, 0x8c, 0x6b, 0xfa, 0xb2, 0x8c, 0x0b, 0x39, 0xf5, 0xd2, 0xdb, 0x0e, 0xb9,
	0x92, 0x53, 0xf4, 0x09, 0xec, 0xe2, 0x9c, 0x17, 0x4c, 0xfb, 0x67, 0x7e, 0xe4, 0x9f, 0xf9, 0x1d,
	0xe1, 0x83, 0xa7, 0x96, 0x36, 0xf4, 0x74, 0xf4, 0x11, 0x34, 0x04, 0x2e, 0x89, 0xb4, 0xbd, 0xbd,
	0x6c, 0x8f, 0xbb, 0xe7, 0x2e, 0x0d, 0x6b, 0xe8, 0xc8, 0xfd, 0x73, 0xd8, 0x75, 0x7e, 0x4c, 0x3e,
	0x9a, 0x6b, 0x3c, 0xb5, 0x75, 0xa8, 0x0f, 0x9d, 0x81, 0xfa, 0xd0, 0x4a, 0x0a, 0x29, 0x09, 0x4b,
	0xca, 0x6a, 0x76, 0x55, 0x76, 0xff, 0x08, 0x1a, 0xd6, 0xd7, 0x7f, 0xbe, 0x9a, 0x0f, 0xee, 0xd4,
	0x5b, 0x89, 0xf5, 0x71, 0x18, 0xac, 0x8f, 0xc3, 0xb3, 0x7f, 0x6a, 0xd0, 0xb9, 0x26, 0x73, 0xca,
	0x2e, 0x71, 0xf9, 0x62, 0x26, 0x51, 0x01, 0x7b, 0xab, 0xe7, 0xd1, 0xc3, 0xed, 0xe3, 0xbd, 0xbf,
	0x15, 0x57, 0x22, 0xfc, 0xf8, 0xa7, 0x3f, 0xff, 0xfa, 0xa5, 0x16, 0x85, 0xa7, 0x91, 0x1a, 0x17,
	0x29, 0x67, 0x59, 0x64, 0x79, 0xd1, 0x2d, 0xa1, 0x73, 0xca, 0x62, 0x3b, 0x0f, 0x67, 0x32, 0xd2,
	0x2b, 0xc7, 0xce, 0x83, 0x53, 0x24, 0xa1, 0xb3, 0xd2, 0x82, 0xe8, 0xf5, 0xad, 0xa3, 0xa6, 0xbf,
	0x0d, 0x7e, 0xf5, 0x98, 0xe6, 0x9b, 0xf8, 0x63, 0x26, 0xe6, 0x8f, 0x70, 0x6f, 0xad, 0x1d, 0xd1,
	0x23, 0xef, 0x7e, 0xb3, 0x99, 0xfb, 0xdb, 0x37, 0x94, 0x08, 0x3f, 0xb5, 0x91, 0xcf, 0xc2, 0xf7,
	0xff, 0x3f, 0x72, 0x46, 0x74, 0xbc, 0xf8, 0xb1, 0xd2, 0xf4, 0x3c, 0x38, 0xfd, 0xfc, 0xf4, 0xbb,
	0x93, 0x8c, 0xea, 0x71, 0x71, 0x33, 0x48, 0x78, 0x1e, 0x7d, 0x4f, 0x98, 0x22, 0x2c, 0x2b, 0x78,
	0xe4, 0xfe, 0xd3, 0x6b, 0xde, 0x6e, 0x76, 0x2d, 0xf8, 0xe1, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x89, 0x5a, 0xea, 0xc1, 0x14, 0x08, 0x00, 0x00,
}
