// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: woa.proto

package woa

import (
	encoding_xml "encoding/xml"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CheckSignatureReq 签名校验接口请求
type CheckSignatureReq struct {
	Signature            string   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce                int64    `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Echostr              string   `protobuf:"bytes,4,opt,name=echostr,proto3" json:"echostr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSignatureReq) Reset()         { *m = CheckSignatureReq{} }
func (m *CheckSignatureReq) String() string { return proto.CompactTextString(m) }
func (*CheckSignatureReq) ProtoMessage()    {}
func (*CheckSignatureReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{0}
}
func (m *CheckSignatureReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSignatureReq.Unmarshal(m, b)
}
func (m *CheckSignatureReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSignatureReq.Marshal(b, m, deterministic)
}
func (m *CheckSignatureReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSignatureReq.Merge(m, src)
}
func (m *CheckSignatureReq) XXX_Size() int {
	return xxx_messageInfo_CheckSignatureReq.Size(m)
}
func (m *CheckSignatureReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSignatureReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSignatureReq proto.InternalMessageInfo

func (m *CheckSignatureReq) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *CheckSignatureReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CheckSignatureReq) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *CheckSignatureReq) GetEchostr() string {
	if m != nil {
		return m.Echostr
	}
	return ""
}

// CheckSignatureReq 签名校验接口回报
type CheckSignatureRsp struct {
	Echostr              string   `protobuf:"bytes,1,opt,name=echostr,proto3" json:"echostr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSignatureRsp) Reset()         { *m = CheckSignatureRsp{} }
func (m *CheckSignatureRsp) String() string { return proto.CompactTextString(m) }
func (*CheckSignatureRsp) ProtoMessage()    {}
func (*CheckSignatureRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{1}
}
func (m *CheckSignatureRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSignatureRsp.Unmarshal(m, b)
}
func (m *CheckSignatureRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSignatureRsp.Marshal(b, m, deterministic)
}
func (m *CheckSignatureRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSignatureRsp.Merge(m, src)
}
func (m *CheckSignatureRsp) XXX_Size() int {
	return xxx_messageInfo_CheckSignatureRsp.Size(m)
}
func (m *CheckSignatureRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSignatureRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSignatureRsp proto.InternalMessageInfo

func (m *CheckSignatureRsp) GetEchostr() string {
	if m != nil {
		return m.Echostr
	}
	return ""
}

// MessageReq 接受普通消息接口请求
type MessageReq struct {
	ToUserName           string   `protobuf:"bytes,1,opt,name=to_user_name,json=toUserName,proto3" json:"to_user_name,omitempty"`
	FromUserName         string   `protobuf:"bytes,2,opt,name=from_user_name,json=fromUserName,proto3" json:"from_user_name,omitempty"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	MsgType              string   `protobuf:"bytes,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Recognition          string   `protobuf:"bytes,6,opt,name=recognition,proto3" json:"recognition,omitempty"`
	MsgId                int64    `protobuf:"varint,7,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgDataId            int64    `protobuf:"varint,8,opt,name=msg_data_id,json=msgDataId,proto3" json:"msg_data_id,omitempty"`
	Idx                  int64    `protobuf:"varint,9,opt,name=idx,proto3" json:"idx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReq) Reset()         { *m = MessageReq{} }
func (m *MessageReq) String() string { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()    {}
func (*MessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{2}
}
func (m *MessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReq.Unmarshal(m, b)
}
func (m *MessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReq.Marshal(b, m, deterministic)
}
func (m *MessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReq.Merge(m, src)
}
func (m *MessageReq) XXX_Size() int {
	return xxx_messageInfo_MessageReq.Size(m)
}
func (m *MessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReq proto.InternalMessageInfo

func (m *MessageReq) GetToUserName() string {
	if m != nil {
		return m.ToUserName
	}
	return ""
}

func (m *MessageReq) GetFromUserName() string {
	if m != nil {
		return m.FromUserName
	}
	return ""
}

func (m *MessageReq) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *MessageReq) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MessageReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageReq) GetRecognition() string {
	if m != nil {
		return m.Recognition
	}
	return ""
}

func (m *MessageReq) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MessageReq) GetMsgDataId() int64 {
	if m != nil {
		return m.MsgDataId
	}
	return 0
}

func (m *MessageReq) GetIdx() int64 {
	if m != nil {
		return m.Idx
	}
	return 0
}

// MessageRsp 接受普通消息接口回包
type MessageRsp struct {
	XMLName              *encoding_xml.Name `protobuf:"bytes,1,opt,name=XMLName,proto3,customtype=encoding/xml.Name" json:"XMLName,omitempty" xml:"xml"`
	ToUserName           *ToUserName        `protobuf:"bytes,2,opt,name=to_user_name,json=toUserName,proto3" json:"to_user_name,omitempty"`
	FromUserName         *FromUserName      `protobuf:"bytes,3,opt,name=from_user_name,json=fromUserName,proto3" json:"from_user_name,omitempty"`
	CreateTime           int64              `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	MsgType              string             `protobuf:"bytes,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content              *Content           `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MessageRsp) Reset()         { *m = MessageRsp{} }
func (m *MessageRsp) String() string { return proto.CompactTextString(m) }
func (*MessageRsp) ProtoMessage()    {}
func (*MessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{3}
}
func (m *MessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRsp.Unmarshal(m, b)
}
func (m *MessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRsp.Marshal(b, m, deterministic)
}
func (m *MessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRsp.Merge(m, src)
}
func (m *MessageRsp) XXX_Size() int {
	return xxx_messageInfo_MessageRsp.Size(m)
}
func (m *MessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRsp proto.InternalMessageInfo

func (m *MessageRsp) GetToUserName() *ToUserName {
	if m != nil {
		return m.ToUserName
	}
	return nil
}

func (m *MessageRsp) GetFromUserName() *FromUserName {
	if m != nil {
		return m.FromUserName
	}
	return nil
}

func (m *MessageRsp) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *MessageRsp) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MessageRsp) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type ToUserName struct {
	ToUserName           string   `protobuf:"bytes,1,opt,name=to_user_name,json=toUserName,proto3" json:"to_user_name,omitempty" xml:",cdata"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToUserName) Reset()         { *m = ToUserName{} }
func (m *ToUserName) String() string { return proto.CompactTextString(m) }
func (*ToUserName) ProtoMessage()    {}
func (*ToUserName) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{4}
}
func (m *ToUserName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToUserName.Unmarshal(m, b)
}
func (m *ToUserName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToUserName.Marshal(b, m, deterministic)
}
func (m *ToUserName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToUserName.Merge(m, src)
}
func (m *ToUserName) XXX_Size() int {
	return xxx_messageInfo_ToUserName.Size(m)
}
func (m *ToUserName) XXX_DiscardUnknown() {
	xxx_messageInfo_ToUserName.DiscardUnknown(m)
}

var xxx_messageInfo_ToUserName proto.InternalMessageInfo

func (m *ToUserName) GetToUserName() string {
	if m != nil {
		return m.ToUserName
	}
	return ""
}

type FromUserName struct {
	FromUserName         string   `protobuf:"bytes,1,opt,name=from_user_name,json=fromUserName,proto3" json:"from_user_name,omitempty" xml:",cdata"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FromUserName) Reset()         { *m = FromUserName{} }
func (m *FromUserName) String() string { return proto.CompactTextString(m) }
func (*FromUserName) ProtoMessage()    {}
func (*FromUserName) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{5}
}
func (m *FromUserName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FromUserName.Unmarshal(m, b)
}
func (m *FromUserName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FromUserName.Marshal(b, m, deterministic)
}
func (m *FromUserName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FromUserName.Merge(m, src)
}
func (m *FromUserName) XXX_Size() int {
	return xxx_messageInfo_FromUserName.Size(m)
}
func (m *FromUserName) XXX_DiscardUnknown() {
	xxx_messageInfo_FromUserName.DiscardUnknown(m)
}

var xxx_messageInfo_FromUserName proto.InternalMessageInfo

func (m *FromUserName) GetFromUserName() string {
	if m != nil {
		return m.FromUserName
	}
	return ""
}

type Content struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty" xml:",cdata"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{6}
}
func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 获取稳定的access token
type GetStableAccessTokenReq struct {
	GrantType            string   `protobuf:"bytes,1,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	Appid                string   `protobuf:"bytes,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	ForceRefresh         bool     `protobuf:"varint,4,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStableAccessTokenReq) Reset()         { *m = GetStableAccessTokenReq{} }
func (m *GetStableAccessTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetStableAccessTokenReq) ProtoMessage()    {}
func (*GetStableAccessTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{7}
}
func (m *GetStableAccessTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStableAccessTokenReq.Unmarshal(m, b)
}
func (m *GetStableAccessTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStableAccessTokenReq.Marshal(b, m, deterministic)
}
func (m *GetStableAccessTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStableAccessTokenReq.Merge(m, src)
}
func (m *GetStableAccessTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetStableAccessTokenReq.Size(m)
}
func (m *GetStableAccessTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStableAccessTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetStableAccessTokenReq proto.InternalMessageInfo

func (m *GetStableAccessTokenReq) GetGrantType() string {
	if m != nil {
		return m.GrantType
	}
	return ""
}

func (m *GetStableAccessTokenReq) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *GetStableAccessTokenReq) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GetStableAccessTokenReq) GetForceRefresh() bool {
	if m != nil {
		return m.ForceRefresh
	}
	return false
}

type GetStableAccessTokenRsp struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpireIn             int64    `protobuf:"varint,2,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStableAccessTokenRsp) Reset()         { *m = GetStableAccessTokenRsp{} }
func (m *GetStableAccessTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetStableAccessTokenRsp) ProtoMessage()    {}
func (*GetStableAccessTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{8}
}
func (m *GetStableAccessTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStableAccessTokenRsp.Unmarshal(m, b)
}
func (m *GetStableAccessTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStableAccessTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetStableAccessTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStableAccessTokenRsp.Merge(m, src)
}
func (m *GetStableAccessTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetStableAccessTokenRsp.Size(m)
}
func (m *GetStableAccessTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStableAccessTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetStableAccessTokenRsp proto.InternalMessageInfo

func (m *GetStableAccessTokenRsp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetStableAccessTokenRsp) GetExpireIn() int64 {
	if m != nil {
		return m.ExpireIn
	}
	return 0
}

// 发送文本消息
type SendKefuMsgReq struct {
	Touser               string        `protobuf:"bytes,1,opt,name=touser,proto3" json:"touser,omitempty"`
	Msgtype              string        `protobuf:"bytes,2,opt,name=msgtype,proto3" json:"msgtype,omitempty"`
	Text                 *KefuTextMsg  `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Image                *KefuImageMsg `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendKefuMsgReq) Reset()         { *m = SendKefuMsgReq{} }
func (m *SendKefuMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendKefuMsgReq) ProtoMessage()    {}
func (*SendKefuMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{9}
}
func (m *SendKefuMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendKefuMsgReq.Unmarshal(m, b)
}
func (m *SendKefuMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendKefuMsgReq.Marshal(b, m, deterministic)
}
func (m *SendKefuMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendKefuMsgReq.Merge(m, src)
}
func (m *SendKefuMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendKefuMsgReq.Size(m)
}
func (m *SendKefuMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendKefuMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendKefuMsgReq proto.InternalMessageInfo

func (m *SendKefuMsgReq) GetTouser() string {
	if m != nil {
		return m.Touser
	}
	return ""
}

func (m *SendKefuMsgReq) GetMsgtype() string {
	if m != nil {
		return m.Msgtype
	}
	return ""
}

func (m *SendKefuMsgReq) GetText() *KefuTextMsg {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *SendKefuMsgReq) GetImage() *KefuImageMsg {
	if m != nil {
		return m.Image
	}
	return nil
}

type KefuTextMsg struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KefuTextMsg) Reset()         { *m = KefuTextMsg{} }
func (m *KefuTextMsg) String() string { return proto.CompactTextString(m) }
func (*KefuTextMsg) ProtoMessage()    {}
func (*KefuTextMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{10}
}
func (m *KefuTextMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KefuTextMsg.Unmarshal(m, b)
}
func (m *KefuTextMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KefuTextMsg.Marshal(b, m, deterministic)
}
func (m *KefuTextMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KefuTextMsg.Merge(m, src)
}
func (m *KefuTextMsg) XXX_Size() int {
	return xxx_messageInfo_KefuTextMsg.Size(m)
}
func (m *KefuTextMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KefuTextMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KefuTextMsg proto.InternalMessageInfo

func (m *KefuTextMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type KefuImageMsg struct {
	MediaId              string   `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KefuImageMsg) Reset()         { *m = KefuImageMsg{} }
func (m *KefuImageMsg) String() string { return proto.CompactTextString(m) }
func (*KefuImageMsg) ProtoMessage()    {}
func (*KefuImageMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{11}
}
func (m *KefuImageMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KefuImageMsg.Unmarshal(m, b)
}
func (m *KefuImageMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KefuImageMsg.Marshal(b, m, deterministic)
}
func (m *KefuImageMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KefuImageMsg.Merge(m, src)
}
func (m *KefuImageMsg) XXX_Size() int {
	return xxx_messageInfo_KefuImageMsg.Size(m)
}
func (m *KefuImageMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KefuImageMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KefuImageMsg proto.InternalMessageInfo

func (m *KefuImageMsg) GetMediaId() string {
	if m != nil {
		return m.MediaId
	}
	return ""
}

type SendKefuMsgRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendKefuMsgRsp) Reset()         { *m = SendKefuMsgRsp{} }
func (m *SendKefuMsgRsp) String() string { return proto.CompactTextString(m) }
func (*SendKefuMsgRsp) ProtoMessage()    {}
func (*SendKefuMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{12}
}
func (m *SendKefuMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendKefuMsgRsp.Unmarshal(m, b)
}
func (m *SendKefuMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendKefuMsgRsp.Marshal(b, m, deterministic)
}
func (m *SendKefuMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendKefuMsgRsp.Merge(m, src)
}
func (m *SendKefuMsgRsp) XXX_Size() int {
	return xxx_messageInfo_SendKefuMsgRsp.Size(m)
}
func (m *SendKefuMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendKefuMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendKefuMsgRsp proto.InternalMessageInfo

// 上传图片消息
type UploadImageMsgRsp struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	MediaId              string   `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageMsgRsp) Reset()         { *m = UploadImageMsgRsp{} }
func (m *UploadImageMsgRsp) String() string { return proto.CompactTextString(m) }
func (*UploadImageMsgRsp) ProtoMessage()    {}
func (*UploadImageMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{13}
}
func (m *UploadImageMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageMsgRsp.Unmarshal(m, b)
}
func (m *UploadImageMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageMsgRsp.Marshal(b, m, deterministic)
}
func (m *UploadImageMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageMsgRsp.Merge(m, src)
}
func (m *UploadImageMsgRsp) XXX_Size() int {
	return xxx_messageInfo_UploadImageMsgRsp.Size(m)
}
func (m *UploadImageMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageMsgRsp proto.InternalMessageInfo

func (m *UploadImageMsgRsp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UploadImageMsgRsp) GetMediaId() string {
	if m != nil {
		return m.MediaId
	}
	return ""
}

func (m *UploadImageMsgRsp) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

// 发送客服输入状态
type SendTypeStatusReq struct {
	Touser               string   `protobuf:"bytes,1,opt,name=touser,proto3" json:"touser,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTypeStatusReq) Reset()         { *m = SendTypeStatusReq{} }
func (m *SendTypeStatusReq) String() string { return proto.CompactTextString(m) }
func (*SendTypeStatusReq) ProtoMessage()    {}
func (*SendTypeStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{14}
}
func (m *SendTypeStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTypeStatusReq.Unmarshal(m, b)
}
func (m *SendTypeStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTypeStatusReq.Marshal(b, m, deterministic)
}
func (m *SendTypeStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTypeStatusReq.Merge(m, src)
}
func (m *SendTypeStatusReq) XXX_Size() int {
	return xxx_messageInfo_SendTypeStatusReq.Size(m)
}
func (m *SendTypeStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTypeStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendTypeStatusReq proto.InternalMessageInfo

func (m *SendTypeStatusReq) GetTouser() string {
	if m != nil {
		return m.Touser
	}
	return ""
}

func (m *SendTypeStatusReq) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type SendTypeStatusRsp struct {
	Errcode              int64    `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTypeStatusRsp) Reset()         { *m = SendTypeStatusRsp{} }
func (m *SendTypeStatusRsp) String() string { return proto.CompactTextString(m) }
func (*SendTypeStatusRsp) ProtoMessage()    {}
func (*SendTypeStatusRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{15}
}
func (m *SendTypeStatusRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTypeStatusRsp.Unmarshal(m, b)
}
func (m *SendTypeStatusRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTypeStatusRsp.Marshal(b, m, deterministic)
}
func (m *SendTypeStatusRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTypeStatusRsp.Merge(m, src)
}
func (m *SendTypeStatusRsp) XXX_Size() int {
	return xxx_messageInfo_SendTypeStatusRsp.Size(m)
}
func (m *SendTypeStatusRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTypeStatusRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendTypeStatusRsp proto.InternalMessageInfo

func (m *SendTypeStatusRsp) GetErrcode() int64 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *SendTypeStatusRsp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckSignatureReq)(nil), "woa.CheckSignatureReq")
	proto.RegisterType((*CheckSignatureRsp)(nil), "woa.CheckSignatureRsp")
	proto.RegisterType((*MessageReq)(nil), "woa.MessageReq")
	proto.RegisterType((*MessageRsp)(nil), "woa.MessageRsp")
	proto.RegisterType((*ToUserName)(nil), "woa.ToUserName")
	proto.RegisterType((*FromUserName)(nil), "woa.FromUserName")
	proto.RegisterType((*Content)(nil), "woa.Content")
	proto.RegisterType((*GetStableAccessTokenReq)(nil), "woa.GetStableAccessTokenReq")
	proto.RegisterType((*GetStableAccessTokenRsp)(nil), "woa.GetStableAccessTokenRsp")
	proto.RegisterType((*SendKefuMsgReq)(nil), "woa.SendKefuMsgReq")
	proto.RegisterType((*KefuTextMsg)(nil), "woa.KefuTextMsg")
	proto.RegisterType((*KefuImageMsg)(nil), "woa.KefuImageMsg")
	proto.RegisterType((*SendKefuMsgRsp)(nil), "woa.SendKefuMsgRsp")
	proto.RegisterType((*UploadImageMsgRsp)(nil), "woa.UploadImageMsgRsp")
	proto.RegisterType((*SendTypeStatusReq)(nil), "woa.SendTypeStatusReq")
	proto.RegisterType((*SendTypeStatusRsp)(nil), "woa.SendTypeStatusRsp")
}

func init() { proto.RegisterFile("woa.proto", fileDescriptor_105fe7df5fe4560f) }

var fileDescriptor_105fe7df5fe4560f = []byte{
	// 933 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0x4f, 0x6f, 0x5b, 0x45,
	0x10, 0x97, 0xed, 0xc4, 0x8e, 0xc7, 0xa6, 0xc4, 0xab, 0x90, 0xba, 0xa1, 0x24, 0x66, 0x89, 0x68,
	0x89, 0x20, 0x16, 0x41, 0x80, 0x54, 0x71, 0xa0, 0x29, 0x14, 0x59, 0x90, 0x4a, 0xd8, 0xae, 0x04,
	0x5c, 0xac, 0xf5, 0x7b, 0x93, 0x97, 0x47, 0xbd, 0xbb, 0x8f, 0xdd, 0x75, 0xe2, 0x9e, 0x90, 0xb8,
	0x72, 0x42, 0x88, 0x0b, 0xdf, 0x89, 0x13, 0x37, 0x0e, 0x39, 0xf1, 0x09, 0xfa, 0x09, 0xd0, 0xfe,
	0x79, 0xf6, 0x7b, 0x4d, 0x52, 0x6e, 0x3b, 0xbf, 0x99, 0x9d, 0x3f, 0xbf, 0x9d, 0x99, 0x85, 0xe6,
	0x85, 0x64, 0x87, 0x99, 0x92, 0x46, 0x92, 0xda, 0x85, 0x64, 0x3b, 0x77, 0x13, 0x29, 0x93, 0x19,
	0xf6, 0x59, 0x96, 0xf6, 0x99, 0x10, 0xd2, 0x30, 0x93, 0x4a, 0xa1, 0xbd, 0xc9, 0xce, 0xed, 0x73,
	0x36, 0x4b, 0x63, 0x66, 0xb0, 0x9f, 0x1f, 0x82, 0x62, 0x2b, 0x91, 0x89, 0x74, 0xc7, 0xbe, 0x3d,
	0x79, 0x94, 0xfe, 0x0c, 0x9d, 0x47, 0x67, 0x18, 0x3d, 0x1b, 0xa5, 0x89, 0x60, 0x66, 0xae, 0x70,
	0x88, 0x3f, 0x91, 0xbb, 0xd0, 0xd4, 0xb9, 0xdc, 0xad, 0xf4, 0x2a, 0xf7, 0x9b, 0xc3, 0x15, 0x60,
	0xb5, 0x26, 0xe5, 0xa8, 0x0d, 0xe3, 0x59, 0xb7, 0xda, 0xab, 0xdc, 0xaf, 0x0d, 0x57, 0x00, 0xd9,
	0x82, 0x75, 0x21, 0x45, 0x84, 0xdd, 0x9a, 0xd3, 0x78, 0x81, 0x74, 0xa1, 0x81, 0xd1, 0x99, 0xd4,
	0x46, 0x75, 0xd7, 0x9c, 0xbf, 0x5c, 0xa4, 0x1f, 0x5c, 0x49, 0x40, 0x67, 0x45, 0xf3, 0x4a, 0xd9,
	0xfc, 0x8f, 0x2a, 0xc0, 0x09, 0x6a, 0xcd, 0x12, 0x97, 0x69, 0x0f, 0xda, 0x46, 0x4e, 0xe6, 0x1a,
	0xd5, 0x44, 0x30, 0x9e, 0x27, 0x0b, 0x46, 0x3e, 0xd5, 0xa8, 0x9e, 0x30, 0x8e, 0x64, 0x1f, 0x6e,
	0x9d, 0x2a, 0xc9, 0x0b, 0x36, 0x55, 0x67, 0xd3, 0xb6, 0xe8, 0xd2, 0x6a, 0x0f, 0x5a, 0x91, 0x42,
	0x66, 0x70, 0x62, 0x2b, 0x09, 0xb9, 0x83, 0x87, 0xc6, 0x29, 0x47, 0x72, 0x07, 0x36, 0xb8, 0x4e,
	0x26, 0xe6, 0x79, 0x86, 0x79, 0x05, 0x5c, 0x27, 0xe3, 0xe7, 0x99, 0xab, 0x2d, 0x92, 0xc2, 0xa0,
	0x30, 0xdd, 0x75, 0xaf, 0x09, 0x22, 0xe9, 0x41, 0x4b, 0x61, 0x24, 0x13, 0x91, 0xda, 0x17, 0xea,
	0xd6, 0x9d, 0xb6, 0x08, 0x91, 0x37, 0xa0, 0x6e, 0xdd, 0xa6, 0x71, 0xb7, 0xe1, 0xe9, 0xe2, 0x3a,
	0x19, 0xc4, 0x64, 0x17, 0x5a, 0x16, 0x8e, 0x99, 0x61, 0x56, 0xb7, 0xe1, 0x49, 0xe6, 0x3a, 0xf9,
	0x82, 0x19, 0x36, 0x88, 0xc9, 0x26, 0xd4, 0xd2, 0x78, 0xd1, 0x6d, 0x3a, 0xdc, 0x1e, 0xe9, 0x9f,
	0x05, 0x5e, 0x74, 0x46, 0x3e, 0x83, 0xc6, 0x77, 0x27, 0xdf, 0x3c, 0xc9, 0x29, 0x69, 0x1f, 0xd3,
	0x7f, 0x2e, 0xf7, 0x3a, 0x28, 0x22, 0x19, 0xa7, 0x22, 0xe9, 0x2f, 0xf8, 0xec, 0xd0, 0x2a, 0x5f,
	0x5c, 0xee, 0x35, 0x17, 0x7c, 0xf6, 0x80, 0x2e, 0xf8, 0x8c, 0x0e, 0xf3, 0x2b, 0xe4, 0xc3, 0x97,
	0x58, 0xb5, 0x8c, 0xb5, 0x8e, 0x5e, 0x3f, 0xb4, 0x8d, 0x38, 0x5e, 0x52, 0x5b, 0xa2, 0xf9, 0xd3,
	0x2b, 0x34, 0xd7, 0xdc, 0xa5, 0x8e, 0xbb, 0xf4, 0xb8, 0xc0, 0xf5, 0xab, 0x99, 0x5f, 0x7b, 0x25,
	0xf3, 0xeb, 0x65, 0xe6, 0xdf, 0x5d, 0x31, 0x5f, 0x77, 0xd1, 0xda, 0x2e, 0xda, 0x23, 0x8f, 0x2d,
	0xdf, 0x81, 0x7e, 0x0e, 0xb0, 0x4a, 0x9b, 0x1c, 0x5d, 0xd7, 0x33, 0xc7, 0x9b, 0x2f, 0x2e, 0xf7,
	0xda, 0x8e, 0x8b, 0xf7, 0x23, 0xcb, 0x3b, 0x2d, 0x96, 0x47, 0x1f, 0x43, 0xbb, 0x58, 0x03, 0xf9,
	0xe4, 0x4a, 0xb9, 0x37, 0x79, 0x29, 0x55, 0x4b, 0x3f, 0x86, 0x46, 0xc8, 0x8e, 0x1c, 0xac, 0x92,
	0xbf, 0xe9, 0xee, 0xb2, 0x80, 0x5f, 0x2b, 0x70, 0xfb, 0x2b, 0x34, 0x23, 0xc3, 0xa6, 0x33, 0x7c,
	0x18, 0x45, 0xa8, 0xf5, 0x58, 0x3e, 0x43, 0x61, 0x47, 0xe0, 0x2d, 0x80, 0x44, 0x31, 0x61, 0x3c,
	0x43, 0x61, 0x5a, 0x1d, 0xe2, 0x38, 0xda, 0x82, 0x75, 0x96, 0x65, 0x69, 0x1c, 0xda, 0xde, 0x0b,
	0x64, 0x1b, 0xea, 0x1a, 0x23, 0x85, 0xc6, 0x3d, 0x53, 0x73, 0x18, 0x24, 0xf2, 0x0e, 0xbc, 0x76,
	0x2a, 0x55, 0x84, 0x13, 0x85, 0xa7, 0x0a, 0xf5, 0x99, 0x7b, 0x8f, 0x8d, 0x61, 0xdb, 0x81, 0x43,
	0x8f, 0xd1, 0xef, 0x6f, 0x48, 0x46, 0x67, 0xe4, 0x6d, 0x68, 0x33, 0x87, 0x4c, 0x8c, 0x85, 0x42,
	0x3a, 0x2d, 0xb6, 0xb2, 0x22, 0x6f, 0x42, 0x13, 0x17, 0x59, 0xaa, 0x70, 0x92, 0x8a, 0xb0, 0x3e,
	0x36, 0x3c, 0x30, 0x10, 0xf4, 0xb7, 0x0a, 0xdc, 0x1a, 0xa1, 0x88, 0xbf, 0xc6, 0xd3, 0xf9, 0x89,
	0x4e, 0x6c, 0x7d, 0xdb, 0x50, 0x37, 0xd2, 0xf2, 0x1c, 0x9c, 0x05, 0xc9, 0x8e, 0x1d, 0xd7, 0x89,
	0x2b, 0xba, 0xba, 0x6c, 0x0b, 0x2b, 0x92, 0x7d, 0x58, 0x33, 0xb8, 0x30, 0xa1, 0x03, 0x37, 0x5d,
	0x4f, 0x58, 0x87, 0x63, 0x5c, 0x18, 0xeb, 0xd4, 0x69, 0xc9, 0x3d, 0x58, 0x4f, 0x39, 0x4b, 0x7c,
	0xcb, 0xe5, 0x8d, 0x6a, 0xcd, 0x06, 0x16, 0xb5, 0x76, 0x5e, 0x4f, 0xef, 0x41, 0xab, 0x70, 0xbb,
	0x38, 0xee, 0x95, 0xd2, 0xb8, 0xd3, 0xf7, 0xa0, 0x5d, 0xbc, 0xef, 0x3a, 0x17, 0xe3, 0xd4, 0x8d,
	0x70, 0x30, 0x75, 0xf2, 0x20, 0xa6, 0x9b, 0xe5, 0x32, 0x75, 0x46, 0x19, 0x74, 0x9e, 0x66, 0x33,
	0xc9, 0xe2, 0x65, 0x78, 0x9d, 0x11, 0x02, 0x6b, 0x85, 0x57, 0x75, 0xe7, 0x92, 0xd7, 0x6a, 0xc9,
	0xab, 0x6d, 0x05, 0x3f, 0x38, 0xf1, 0x84, 0x99, 0xb0, 0xc4, 0x9a, 0x01, 0x79, 0x68, 0xe8, 0x97,
	0xd0, 0xb1, 0x41, 0x6d, 0x5b, 0x8c, 0x0c, 0x33, 0x73, 0xfd, 0x3f, 0xf4, 0x46, 0x92, 0x73, 0x26,
	0x96, 0x51, 0x82, 0x78, 0x8d, 0x9b, 0xb0, 0xb1, 0x95, 0x8a, 0x64, 0xec, 0x93, 0xad, 0x0d, 0x73,
	0xd1, 0x06, 0x40, 0xa5, 0xb8, 0x4e, 0x82, 0x9f, 0x20, 0x1d, 0xfd, 0x55, 0x01, 0x38, 0x66, 0xda,
	0x96, 0x3a, 0x3a, 0x57, 0x64, 0x06, 0xb7, 0xca, 0xff, 0x00, 0xd9, 0xf6, 0xc3, 0xfc, 0xf2, 0xef,
	0xb4, 0x73, 0x2d, 0xae, 0x33, 0x7a, 0xf0, 0xcb, 0xdf, 0xff, 0xfe, 0x5e, 0xdd, 0x27, 0x77, 0xfa,
	0x56, 0x3f, 0x65, 0x1a, 0x27, 0x76, 0x71, 0xe8, 0x73, 0xd5, 0xe7, 0x7e, 0x33, 0x4e, 0xf3, 0x6f,
	0x84, 0x7c, 0x0b, 0x8d, 0xb0, 0x2d, 0x89, 0x5f, 0x6b, 0xab, 0x3f, 0x65, 0xa7, 0x0c, 0xe8, 0x8c,
	0xee, 0x3b, 0xc7, 0xbb, 0xf4, 0x66, 0xc7, 0x0f, 0x2a, 0x07, 0xc7, 0xbd, 0x1f, 0x76, 0x93, 0xd4,
	0x9c, 0xcd, 0xa7, 0x87, 0x91, 0xe4, 0xfd, 0x1f, 0x51, 0x68, 0x14, 0xc9, 0x5c, 0xf6, 0xfd, 0x97,
	0x7b, 0x21, 0xd9, 0xb4, 0xee, 0x8e, 0x1f, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xa7, 0x92,
	0xaa, 0xd1, 0x07, 0x00, 0x00,
}
