// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: woa.proto

package woa

import (
	encoding_xml "encoding/xml"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CheckSignatureReq 签名校验接口请求
type CheckSignatureReq struct {
	Signature            string   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce                int64    `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Echostr              string   `protobuf:"bytes,4,opt,name=echostr,proto3" json:"echostr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSignatureReq) Reset()         { *m = CheckSignatureReq{} }
func (m *CheckSignatureReq) String() string { return proto.CompactTextString(m) }
func (*CheckSignatureReq) ProtoMessage()    {}
func (*CheckSignatureReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{0}
}
func (m *CheckSignatureReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSignatureReq.Unmarshal(m, b)
}
func (m *CheckSignatureReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSignatureReq.Marshal(b, m, deterministic)
}
func (m *CheckSignatureReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSignatureReq.Merge(m, src)
}
func (m *CheckSignatureReq) XXX_Size() int {
	return xxx_messageInfo_CheckSignatureReq.Size(m)
}
func (m *CheckSignatureReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSignatureReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSignatureReq proto.InternalMessageInfo

func (m *CheckSignatureReq) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *CheckSignatureReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CheckSignatureReq) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *CheckSignatureReq) GetEchostr() string {
	if m != nil {
		return m.Echostr
	}
	return ""
}

// CheckSignatureReq 签名校验接口回报
type CheckSignatureRsp struct {
	Echostr              string   `protobuf:"bytes,1,opt,name=echostr,proto3" json:"echostr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSignatureRsp) Reset()         { *m = CheckSignatureRsp{} }
func (m *CheckSignatureRsp) String() string { return proto.CompactTextString(m) }
func (*CheckSignatureRsp) ProtoMessage()    {}
func (*CheckSignatureRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{1}
}
func (m *CheckSignatureRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSignatureRsp.Unmarshal(m, b)
}
func (m *CheckSignatureRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSignatureRsp.Marshal(b, m, deterministic)
}
func (m *CheckSignatureRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSignatureRsp.Merge(m, src)
}
func (m *CheckSignatureRsp) XXX_Size() int {
	return xxx_messageInfo_CheckSignatureRsp.Size(m)
}
func (m *CheckSignatureRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSignatureRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSignatureRsp proto.InternalMessageInfo

func (m *CheckSignatureRsp) GetEchostr() string {
	if m != nil {
		return m.Echostr
	}
	return ""
}

// MessageReq 接受普通消息接口请求
type MessageReq struct {
	ToUserName           string   `protobuf:"bytes,1,opt,name=to_user_name,json=toUserName,proto3" json:"to_user_name,omitempty"`
	FromUserName         string   `protobuf:"bytes,2,opt,name=from_user_name,json=fromUserName,proto3" json:"from_user_name,omitempty"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	MsgType              string   `protobuf:"bytes,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	MsgId                int64    `protobuf:"varint,7,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgDataId            int64    `protobuf:"varint,8,opt,name=msg_data_id,json=msgDataId,proto3" json:"msg_data_id,omitempty"`
	Idx                  int64    `protobuf:"varint,9,opt,name=idx,proto3" json:"idx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReq) Reset()         { *m = MessageReq{} }
func (m *MessageReq) String() string { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()    {}
func (*MessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{2}
}
func (m *MessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReq.Unmarshal(m, b)
}
func (m *MessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReq.Marshal(b, m, deterministic)
}
func (m *MessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReq.Merge(m, src)
}
func (m *MessageReq) XXX_Size() int {
	return xxx_messageInfo_MessageReq.Size(m)
}
func (m *MessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReq proto.InternalMessageInfo

func (m *MessageReq) GetToUserName() string {
	if m != nil {
		return m.ToUserName
	}
	return ""
}

func (m *MessageReq) GetFromUserName() string {
	if m != nil {
		return m.FromUserName
	}
	return ""
}

func (m *MessageReq) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *MessageReq) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MessageReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageReq) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MessageReq) GetMsgDataId() int64 {
	if m != nil {
		return m.MsgDataId
	}
	return 0
}

func (m *MessageReq) GetIdx() int64 {
	if m != nil {
		return m.Idx
	}
	return 0
}

// MessageRsp 接受普通消息接口回包
type MessageRsp struct {
	XMLName              *encoding_xml.Name `protobuf:"bytes,1,opt,name=XMLName,proto3,customtype=encoding/xml.Name" json:"XMLName,omitempty" xml:"xml"`
	ToUserName           *ToUserName        `protobuf:"bytes,2,opt,name=to_user_name,json=toUserName,proto3" json:"to_user_name,omitempty"`
	FromUserName         *FromUserName      `protobuf:"bytes,3,opt,name=from_user_name,json=fromUserName,proto3" json:"from_user_name,omitempty"`
	CreateTime           int64              `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	MsgType              string             `protobuf:"bytes,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content              *Content           `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MessageRsp) Reset()         { *m = MessageRsp{} }
func (m *MessageRsp) String() string { return proto.CompactTextString(m) }
func (*MessageRsp) ProtoMessage()    {}
func (*MessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{3}
}
func (m *MessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRsp.Unmarshal(m, b)
}
func (m *MessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRsp.Marshal(b, m, deterministic)
}
func (m *MessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRsp.Merge(m, src)
}
func (m *MessageRsp) XXX_Size() int {
	return xxx_messageInfo_MessageRsp.Size(m)
}
func (m *MessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRsp proto.InternalMessageInfo

func (m *MessageRsp) GetToUserName() *ToUserName {
	if m != nil {
		return m.ToUserName
	}
	return nil
}

func (m *MessageRsp) GetFromUserName() *FromUserName {
	if m != nil {
		return m.FromUserName
	}
	return nil
}

func (m *MessageRsp) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *MessageRsp) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *MessageRsp) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type ToUserName struct {
	ToUserName           string   `protobuf:"bytes,1,opt,name=to_user_name,json=toUserName,proto3" json:"to_user_name,omitempty" xml:",cdata"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToUserName) Reset()         { *m = ToUserName{} }
func (m *ToUserName) String() string { return proto.CompactTextString(m) }
func (*ToUserName) ProtoMessage()    {}
func (*ToUserName) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{4}
}
func (m *ToUserName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToUserName.Unmarshal(m, b)
}
func (m *ToUserName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToUserName.Marshal(b, m, deterministic)
}
func (m *ToUserName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToUserName.Merge(m, src)
}
func (m *ToUserName) XXX_Size() int {
	return xxx_messageInfo_ToUserName.Size(m)
}
func (m *ToUserName) XXX_DiscardUnknown() {
	xxx_messageInfo_ToUserName.DiscardUnknown(m)
}

var xxx_messageInfo_ToUserName proto.InternalMessageInfo

func (m *ToUserName) GetToUserName() string {
	if m != nil {
		return m.ToUserName
	}
	return ""
}

type FromUserName struct {
	FromUserName         string   `protobuf:"bytes,1,opt,name=from_user_name,json=fromUserName,proto3" json:"from_user_name,omitempty" xml:",cdata"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FromUserName) Reset()         { *m = FromUserName{} }
func (m *FromUserName) String() string { return proto.CompactTextString(m) }
func (*FromUserName) ProtoMessage()    {}
func (*FromUserName) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{5}
}
func (m *FromUserName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FromUserName.Unmarshal(m, b)
}
func (m *FromUserName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FromUserName.Marshal(b, m, deterministic)
}
func (m *FromUserName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FromUserName.Merge(m, src)
}
func (m *FromUserName) XXX_Size() int {
	return xxx_messageInfo_FromUserName.Size(m)
}
func (m *FromUserName) XXX_DiscardUnknown() {
	xxx_messageInfo_FromUserName.DiscardUnknown(m)
}

var xxx_messageInfo_FromUserName proto.InternalMessageInfo

func (m *FromUserName) GetFromUserName() string {
	if m != nil {
		return m.FromUserName
	}
	return ""
}

type Content struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty" xml:",cdata"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{6}
}
func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GetAccessTokenRsp struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpireIn             int64    `protobuf:"varint,2,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRsp) Reset()         { *m = GetAccessTokenRsp{} }
func (m *GetAccessTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRsp) ProtoMessage()    {}
func (*GetAccessTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{7}
}
func (m *GetAccessTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRsp.Unmarshal(m, b)
}
func (m *GetAccessTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRsp.Merge(m, src)
}
func (m *GetAccessTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRsp.Size(m)
}
func (m *GetAccessTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRsp proto.InternalMessageInfo

func (m *GetAccessTokenRsp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAccessTokenRsp) GetExpireIn() int64 {
	if m != nil {
		return m.ExpireIn
	}
	return 0
}

type SendKefuMsgReq struct {
	Touser               string       `protobuf:"bytes,1,opt,name=touser,proto3" json:"touser,omitempty"`
	Msgtype              string       `protobuf:"bytes,2,opt,name=msgtype,proto3" json:"msgtype,omitempty"`
	Text                 *KefuTextMsg `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendKefuMsgReq) Reset()         { *m = SendKefuMsgReq{} }
func (m *SendKefuMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendKefuMsgReq) ProtoMessage()    {}
func (*SendKefuMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{8}
}
func (m *SendKefuMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendKefuMsgReq.Unmarshal(m, b)
}
func (m *SendKefuMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendKefuMsgReq.Marshal(b, m, deterministic)
}
func (m *SendKefuMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendKefuMsgReq.Merge(m, src)
}
func (m *SendKefuMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendKefuMsgReq.Size(m)
}
func (m *SendKefuMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendKefuMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendKefuMsgReq proto.InternalMessageInfo

func (m *SendKefuMsgReq) GetTouser() string {
	if m != nil {
		return m.Touser
	}
	return ""
}

func (m *SendKefuMsgReq) GetMsgtype() string {
	if m != nil {
		return m.Msgtype
	}
	return ""
}

func (m *SendKefuMsgReq) GetText() *KefuTextMsg {
	if m != nil {
		return m.Text
	}
	return nil
}

type KefuTextMsg struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KefuTextMsg) Reset()         { *m = KefuTextMsg{} }
func (m *KefuTextMsg) String() string { return proto.CompactTextString(m) }
func (*KefuTextMsg) ProtoMessage()    {}
func (*KefuTextMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{9}
}
func (m *KefuTextMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KefuTextMsg.Unmarshal(m, b)
}
func (m *KefuTextMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KefuTextMsg.Marshal(b, m, deterministic)
}
func (m *KefuTextMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KefuTextMsg.Merge(m, src)
}
func (m *KefuTextMsg) XXX_Size() int {
	return xxx_messageInfo_KefuTextMsg.Size(m)
}
func (m *KefuTextMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KefuTextMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KefuTextMsg proto.InternalMessageInfo

func (m *KefuTextMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendKefuMsgRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendKefuMsgRsp) Reset()         { *m = SendKefuMsgRsp{} }
func (m *SendKefuMsgRsp) String() string { return proto.CompactTextString(m) }
func (*SendKefuMsgRsp) ProtoMessage()    {}
func (*SendKefuMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{10}
}
func (m *SendKefuMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendKefuMsgRsp.Unmarshal(m, b)
}
func (m *SendKefuMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendKefuMsgRsp.Marshal(b, m, deterministic)
}
func (m *SendKefuMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendKefuMsgRsp.Merge(m, src)
}
func (m *SendKefuMsgRsp) XXX_Size() int {
	return xxx_messageInfo_SendKefuMsgRsp.Size(m)
}
func (m *SendKefuMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendKefuMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendKefuMsgRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CheckSignatureReq)(nil), "woa.CheckSignatureReq")
	proto.RegisterType((*CheckSignatureRsp)(nil), "woa.CheckSignatureRsp")
	proto.RegisterType((*MessageReq)(nil), "woa.MessageReq")
	proto.RegisterType((*MessageRsp)(nil), "woa.MessageRsp")
	proto.RegisterType((*ToUserName)(nil), "woa.ToUserName")
	proto.RegisterType((*FromUserName)(nil), "woa.FromUserName")
	proto.RegisterType((*Content)(nil), "woa.Content")
	proto.RegisterType((*GetAccessTokenRsp)(nil), "woa.GetAccessTokenRsp")
	proto.RegisterType((*SendKefuMsgReq)(nil), "woa.SendKefuMsgReq")
	proto.RegisterType((*KefuTextMsg)(nil), "woa.KefuTextMsg")
	proto.RegisterType((*SendKefuMsgRsp)(nil), "woa.SendKefuMsgRsp")
}

func init() { proto.RegisterFile("woa.proto", fileDescriptor_105fe7df5fe4560f) }

var fileDescriptor_105fe7df5fe4560f = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcf, 0x6e, 0x33, 0x35,
	0x10, 0xd7, 0x26, 0x6d, 0xd2, 0x4c, 0xa2, 0x92, 0x58, 0xa5, 0x6c, 0x43, 0xd5, 0x04, 0x2b, 0x82,
	0xaa, 0x82, 0xac, 0x08, 0x02, 0xa4, 0x8a, 0x03, 0xa4, 0xa8, 0xa8, 0x82, 0x54, 0x22, 0x09, 0x12,
	0xe2, 0x12, 0x39, 0xbb, 0xae, 0xb3, 0x34, 0xb6, 0x97, 0xb5, 0xd3, 0xa6, 0x27, 0x24, 0x5e, 0x81,
	0x1b, 0xef, 0xc4, 0x89, 0x1b, 0x87, 0x9e, 0xbe, 0x27, 0xe8, 0xf7, 0x02, 0x9f, 0xec, 0xdd, 0x4d,
	0xb2, 0xfd, 0x77, 0xf3, 0xfc, 0x66, 0x3c, 0x9e, 0xdf, 0xcf, 0x33, 0x03, 0x95, 0x5b, 0x49, 0xba,
	0x51, 0x2c, 0xb5, 0x44, 0xc5, 0x5b, 0x49, 0x9a, 0x87, 0x4c, 0x4a, 0x36, 0xa7, 0x1e, 0x89, 0x42,
	0x8f, 0x08, 0x21, 0x35, 0xd1, 0xa1, 0x14, 0x2a, 0x09, 0x69, 0x7e, 0x70, 0x43, 0xe6, 0x61, 0x40,
	0x34, 0xf5, 0xb2, 0x43, 0xea, 0xd8, 0x63, 0x92, 0x49, 0x7b, 0xf4, 0xcc, 0x29, 0x41, 0xf1, 0x9f,
	0xd0, 0x38, 0x9b, 0x51, 0xff, 0x7a, 0x14, 0x32, 0x41, 0xf4, 0x22, 0xa6, 0x43, 0xfa, 0x07, 0x3a,
	0x84, 0x8a, 0xca, 0x6c, 0xd7, 0x69, 0x3b, 0xc7, 0x95, 0xe1, 0x1a, 0x30, 0x5e, 0x1d, 0x72, 0xaa,
	0x34, 0xe1, 0x91, 0x5b, 0x68, 0x3b, 0xc7, 0xc5, 0xe1, 0x1a, 0x40, 0x7b, 0xb0, 0x2d, 0xa4, 0xf0,
	0xa9, 0x5b, 0xb4, 0x9e, 0xc4, 0x40, 0x2e, 0x94, 0xa9, 0x3f, 0x93, 0x4a, 0xc7, 0xee, 0x96, 0xcd,
	0x97, 0x99, 0xf8, 0xb3, 0x27, 0x05, 0xa8, 0x68, 0x33, 0xdc, 0xc9, 0x87, 0xbf, 0x75, 0x00, 0x06,
	0x54, 0x29, 0xc2, 0x6c, 0xa5, 0x6d, 0xa8, 0x69, 0x39, 0x59, 0x28, 0x1a, 0x4f, 0x04, 0xe1, 0x59,
	0xb1, 0xa0, 0xe5, 0x2f, 0x8a, 0xc6, 0x97, 0x84, 0x53, 0xd4, 0x81, 0xdd, 0xab, 0x58, 0xf2, 0x8d,
	0x98, 0x82, 0x8d, 0xa9, 0x19, 0x74, 0x15, 0xd5, 0x82, 0xaa, 0x1f, 0x53, 0xa2, 0xe9, 0xc4, 0x30,
	0x49, 0x6b, 0x87, 0x04, 0x1a, 0x87, 0x9c, 0xa2, 0x03, 0xd8, 0xe1, 0x8a, 0x4d, 0xf4, 0x5d, 0x44,
	0x33, 0x06, 0x5c, 0xb1, 0xf1, 0x5d, 0x64, 0xb9, 0xf9, 0x52, 0x68, 0x2a, 0xb4, 0x5b, 0x4a, 0x3c,
	0xa9, 0x89, 0xde, 0x87, 0x92, 0xb9, 0x14, 0x06, 0x6e, 0x39, 0x11, 0x83, 0x2b, 0x76, 0x11, 0xa0,
	0x23, 0xa8, 0x1a, 0x38, 0x20, 0x9a, 0x18, 0xdf, 0x4e, 0x22, 0x21, 0x57, 0xec, 0x7b, 0xa2, 0xc9,
	0x45, 0x80, 0xea, 0x50, 0x0c, 0x83, 0xa5, 0x5b, 0xb1, 0xb8, 0x39, 0xe2, 0x7f, 0x0a, 0x6b, 0xd6,
	0x2a, 0x42, 0xdf, 0x40, 0xf9, 0xd7, 0xc1, 0x4f, 0x97, 0x19, 0xe1, 0x5a, 0x1f, 0xff, 0x7f, 0xdf,
	0x6a, 0x50, 0xe1, 0xcb, 0x20, 0x14, 0xcc, 0x5b, 0xf2, 0x79, 0xd7, 0x38, 0x1f, 0xee, 0x5b, 0x95,
	0x25, 0x9f, 0x9f, 0xe2, 0x25, 0x9f, 0xe3, 0x61, 0x76, 0x05, 0x7d, 0xfe, 0x48, 0x33, 0xa3, 0x47,
	0xb5, 0xf7, 0x5e, 0xd7, 0xb4, 0xd9, 0x78, 0x25, 0x5c, 0x4e, 0xc4, 0xaf, 0x9f, 0x88, 0x58, 0xb4,
	0x97, 0x1a, 0xf6, 0xd2, 0xf9, 0x86, 0x92, 0xaf, 0xeb, 0xba, 0xf5, 0xaa, 0xae, 0xdb, 0x79, 0x5d,
	0x3f, 0xce, 0xeb, 0x5a, 0xed, 0xd5, 0xec, 0x6b, 0x67, 0x09, 0xb6, 0x52, 0x19, 0x7f, 0x0b, 0xb0,
	0x2e, 0x1b, 0xf5, 0x9e, 0xeb, 0x88, 0x7e, 0xfd, 0xe1, 0xbe, 0x55, 0xb3, 0x5a, 0x7c, 0xea, 0x1b,
	0xdd, 0xf1, 0x26, 0x3d, 0x7c, 0x0e, 0xb5, 0x4d, 0x0e, 0xe8, 0xab, 0x27, 0x74, 0x5f, 0xca, 0x92,
	0x63, 0x8b, 0xbf, 0x84, 0x72, 0x5a, 0x1d, 0x3a, 0x59, 0x17, 0xff, 0xd2, 0xdd, 0x15, 0x81, 0x11,
	0x34, 0x7e, 0xa0, 0xfa, 0x3b, 0xdf, 0xa7, 0x4a, 0x8d, 0xe5, 0x35, 0x15, 0xe6, 0x8f, 0x3f, 0x82,
	0x1a, 0xb1, 0xc8, 0x44, 0x1b, 0x28, 0xed, 0xec, 0x2a, 0x59, 0x47, 0xa1, 0x0f, 0xa1, 0x42, 0x97,
	0x51, 0x18, 0xd3, 0x49, 0x28, 0xd2, 0x41, 0xdc, 0x49, 0x80, 0x0b, 0x81, 0x67, 0xb0, 0x3b, 0xa2,
	0x22, 0xf8, 0x91, 0x5e, 0x2d, 0x06, 0x8a, 0x99, 0x59, 0xd9, 0x87, 0x92, 0x96, 0x86, 0x52, 0x9a,
	0x2b, 0xb5, 0x4c, 0xff, 0x72, 0xc5, 0xec, 0x0f, 0x14, 0x56, 0x3f, 0x60, 0x4c, 0xd4, 0x81, 0x2d,
	0x4d, 0x97, 0x3a, 0xfd, 0xec, 0xba, 0x95, 0xdf, 0x24, 0x1c, 0xd3, 0xa5, 0x36, 0x49, 0xad, 0x17,
	0x7f, 0x02, 0xd5, 0x0d, 0x70, 0x73, 0x1c, 0x9c, 0xdc, 0x38, 0xe0, 0x7a, 0xbe, 0x24, 0x15, 0xf5,
	0xfe, 0x75, 0x00, 0xfa, 0x44, 0xd1, 0x81, 0x62, 0xa3, 0x9b, 0x18, 0xcd, 0x61, 0x37, 0xbf, 0x0b,
	0xd0, 0x7e, 0xf2, 0xe5, 0x8f, 0x37, 0x54, 0xf3, 0x59, 0x5c, 0x45, 0xf8, 0xe4, 0xaf, 0xff, 0xde,
	0xfc, 0x5d, 0xe8, 0xa0, 0x03, 0xcf, 0xf8, 0xa7, 0x44, 0xd1, 0x89, 0x69, 0x2f, 0x75, 0x13, 0x7b,
	0x3c, 0x99, 0x9f, 0x69, 0xb6, 0x4a, 0xd0, 0xcf, 0x50, 0x4e, 0x67, 0x0a, 0x25, 0xcd, 0xbf, 0xde,
	0x2b, 0xcd, 0x3c, 0xa0, 0x22, 0xdc, 0xb1, 0x89, 0x8f, 0xf0, 0xcb, 0x89, 0x4f, 0x9d, 0x93, 0x7e,
	0xfb, 0xb7, 0x23, 0x16, 0xea, 0xd9, 0x62, 0xda, 0xf5, 0x25, 0xf7, 0x7e, 0xa7, 0x42, 0x51, 0xc1,
	0x16, 0xd2, 0x4b, 0xd6, 0xee, 0xad, 0x24, 0xd3, 0x92, 0x3d, 0x7e, 0xf1, 0x2e, 0x00, 0x00, 0xff,
	0xff, 0x41, 0x52, 0x30, 0x55, 0xd5, 0x05, 0x00, 0x00,
}
