// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: woa.proto

package woa

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CheckSignatureReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CheckSignatureReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckSignatureReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckSignatureReqMultiError, or nil if none found.
func (m *CheckSignatureReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckSignatureReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Signature

	// no validation rules for Timestamp

	// no validation rules for Nonce

	// no validation rules for Echostr

	if len(errors) > 0 {
		return CheckSignatureReqMultiError(errors)
	}

	return nil
}

// CheckSignatureReqMultiError is an error wrapping multiple validation errors
// returned by CheckSignatureReq.ValidateAll() if the designated constraints
// aren't met.
type CheckSignatureReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckSignatureReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckSignatureReqMultiError) AllErrors() []error { return m }

// CheckSignatureReqValidationError is the validation error returned by
// CheckSignatureReq.Validate if the designated constraints aren't met.
type CheckSignatureReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckSignatureReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckSignatureReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckSignatureReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckSignatureReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckSignatureReqValidationError) ErrorName() string {
	return "CheckSignatureReqValidationError"
}

// Error satisfies the builtin error interface
func (e CheckSignatureReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckSignatureReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckSignatureReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckSignatureReqValidationError{}

// Validate checks the field values on CheckSignatureRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CheckSignatureRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckSignatureRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckSignatureRspMultiError, or nil if none found.
func (m *CheckSignatureRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckSignatureRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Echostr

	if len(errors) > 0 {
		return CheckSignatureRspMultiError(errors)
	}

	return nil
}

// CheckSignatureRspMultiError is an error wrapping multiple validation errors
// returned by CheckSignatureRsp.ValidateAll() if the designated constraints
// aren't met.
type CheckSignatureRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckSignatureRspMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckSignatureRspMultiError) AllErrors() []error { return m }

// CheckSignatureRspValidationError is the validation error returned by
// CheckSignatureRsp.Validate if the designated constraints aren't met.
type CheckSignatureRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckSignatureRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckSignatureRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckSignatureRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckSignatureRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckSignatureRspValidationError) ErrorName() string {
	return "CheckSignatureRspValidationError"
}

// Error satisfies the builtin error interface
func (e CheckSignatureRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckSignatureRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckSignatureRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckSignatureRspValidationError{}

// Validate checks the field values on MessageReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MessageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessageReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MessageReqMultiError, or
// nil if none found.
func (m *MessageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *MessageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ToUserName

	// no validation rules for FromUserName

	// no validation rules for CreateTime

	// no validation rules for MsgType

	// no validation rules for Content

	// no validation rules for MsgId

	// no validation rules for MsgDataId

	// no validation rules for Idx

	if len(errors) > 0 {
		return MessageReqMultiError(errors)
	}

	return nil
}

// MessageReqMultiError is an error wrapping multiple validation errors
// returned by MessageReq.ValidateAll() if the designated constraints aren't met.
type MessageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageReqMultiError) AllErrors() []error { return m }

// MessageReqValidationError is the validation error returned by
// MessageReq.Validate if the designated constraints aren't met.
type MessageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageReqValidationError) ErrorName() string { return "MessageReqValidationError" }

// Error satisfies the builtin error interface
func (e MessageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageReqValidationError{}

// Validate checks the field values on MessageRsp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MessageRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessageRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MessageRspMultiError, or
// nil if none found.
func (m *MessageRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *MessageRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for XMLName

	if all {
		switch v := interface{}(m.GetToUserName()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MessageRspValidationError{
					field:  "ToUserName",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MessageRspValidationError{
					field:  "ToUserName",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetToUserName()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageRspValidationError{
				field:  "ToUserName",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetFromUserName()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MessageRspValidationError{
					field:  "FromUserName",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MessageRspValidationError{
					field:  "FromUserName",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFromUserName()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageRspValidationError{
				field:  "FromUserName",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CreateTime

	// no validation rules for MsgType

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MessageRspValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MessageRspValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageRspValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MessageRspMultiError(errors)
	}

	return nil
}

// MessageRspMultiError is an error wrapping multiple validation errors
// returned by MessageRsp.ValidateAll() if the designated constraints aren't met.
type MessageRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageRspMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageRspMultiError) AllErrors() []error { return m }

// MessageRspValidationError is the validation error returned by
// MessageRsp.Validate if the designated constraints aren't met.
type MessageRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageRspValidationError) ErrorName() string { return "MessageRspValidationError" }

// Error satisfies the builtin error interface
func (e MessageRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageRspValidationError{}

// Validate checks the field values on ToUserName with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ToUserName) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToUserName with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ToUserNameMultiError, or
// nil if none found.
func (m *ToUserName) ValidateAll() error {
	return m.validate(true)
}

func (m *ToUserName) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ToUserName

	if len(errors) > 0 {
		return ToUserNameMultiError(errors)
	}

	return nil
}

// ToUserNameMultiError is an error wrapping multiple validation errors
// returned by ToUserName.ValidateAll() if the designated constraints aren't met.
type ToUserNameMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToUserNameMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToUserNameMultiError) AllErrors() []error { return m }

// ToUserNameValidationError is the validation error returned by
// ToUserName.Validate if the designated constraints aren't met.
type ToUserNameValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToUserNameValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToUserNameValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToUserNameValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToUserNameValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToUserNameValidationError) ErrorName() string { return "ToUserNameValidationError" }

// Error satisfies the builtin error interface
func (e ToUserNameValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToUserName.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToUserNameValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToUserNameValidationError{}

// Validate checks the field values on FromUserName with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FromUserName) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FromUserName with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FromUserNameMultiError, or
// nil if none found.
func (m *FromUserName) ValidateAll() error {
	return m.validate(true)
}

func (m *FromUserName) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FromUserName

	if len(errors) > 0 {
		return FromUserNameMultiError(errors)
	}

	return nil
}

// FromUserNameMultiError is an error wrapping multiple validation errors
// returned by FromUserName.ValidateAll() if the designated constraints aren't met.
type FromUserNameMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FromUserNameMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FromUserNameMultiError) AllErrors() []error { return m }

// FromUserNameValidationError is the validation error returned by
// FromUserName.Validate if the designated constraints aren't met.
type FromUserNameValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FromUserNameValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FromUserNameValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FromUserNameValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FromUserNameValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FromUserNameValidationError) ErrorName() string { return "FromUserNameValidationError" }

// Error satisfies the builtin error interface
func (e FromUserNameValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFromUserName.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FromUserNameValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FromUserNameValidationError{}

// Validate checks the field values on Content with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Content) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Content with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ContentMultiError, or nil if none found.
func (m *Content) ValidateAll() error {
	return m.validate(true)
}

func (m *Content) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Content

	if len(errors) > 0 {
		return ContentMultiError(errors)
	}

	return nil
}

// ContentMultiError is an error wrapping multiple validation errors returned
// by Content.ValidateAll() if the designated constraints aren't met.
type ContentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ContentMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ContentMultiError) AllErrors() []error { return m }

// ContentValidationError is the validation error returned by Content.Validate
// if the designated constraints aren't met.
type ContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContentValidationError) ErrorName() string { return "ContentValidationError" }

// Error satisfies the builtin error interface
func (e ContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContentValidationError{}
