// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: woa.proto

package woa

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CheckSignatureReq 签名校验接口请求
type CheckSignatureReq struct {
	Signature            string   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce                int64    `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Echostr              string   `protobuf:"bytes,4,opt,name=echostr,proto3" json:"echostr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSignatureReq) Reset()         { *m = CheckSignatureReq{} }
func (m *CheckSignatureReq) String() string { return proto.CompactTextString(m) }
func (*CheckSignatureReq) ProtoMessage()    {}
func (*CheckSignatureReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{0}
}
func (m *CheckSignatureReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSignatureReq.Unmarshal(m, b)
}
func (m *CheckSignatureReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSignatureReq.Marshal(b, m, deterministic)
}
func (m *CheckSignatureReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSignatureReq.Merge(m, src)
}
func (m *CheckSignatureReq) XXX_Size() int {
	return xxx_messageInfo_CheckSignatureReq.Size(m)
}
func (m *CheckSignatureReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSignatureReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSignatureReq proto.InternalMessageInfo

func (m *CheckSignatureReq) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *CheckSignatureReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CheckSignatureReq) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *CheckSignatureReq) GetEchostr() string {
	if m != nil {
		return m.Echostr
	}
	return ""
}

// CheckSignatureRsp 签名校验接口回包
type CheckSignatureRsp struct {
	Echostr              string   `protobuf:"bytes,1,opt,name=echostr,proto3" json:"echostr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSignatureRsp) Reset()         { *m = CheckSignatureRsp{} }
func (m *CheckSignatureRsp) String() string { return proto.CompactTextString(m) }
func (*CheckSignatureRsp) ProtoMessage()    {}
func (*CheckSignatureRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{1}
}
func (m *CheckSignatureRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSignatureRsp.Unmarshal(m, b)
}
func (m *CheckSignatureRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSignatureRsp.Marshal(b, m, deterministic)
}
func (m *CheckSignatureRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSignatureRsp.Merge(m, src)
}
func (m *CheckSignatureRsp) XXX_Size() int {
	return xxx_messageInfo_CheckSignatureRsp.Size(m)
}
func (m *CheckSignatureRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSignatureRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSignatureRsp proto.InternalMessageInfo

func (m *CheckSignatureRsp) GetEchostr() string {
	if m != nil {
		return m.Echostr
	}
	return ""
}

// ReceiveMessageReq 接受普通消息接口请求
type ReceiveMessageReq struct {
	ToUserName           string   `protobuf:"bytes,1,opt,name=to_user_name,json=toUserName,proto3" json:"to_user_name,omitempty" xml:"ToUserName"`
	FromUserName         string   `protobuf:"bytes,2,opt,name=from_user_name,json=fromUserName,proto3" json:"from_user_name,omitempty" xml:"FromUserName"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" xml:"CreateTime"`
	MsgType              string   `protobuf:"bytes,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty" xml:"MsgType"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty" xml:"Content"`
	MsgId                int64    `protobuf:"varint,7,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty" xml:"MsgId"`
	MsgDataId            int64    `protobuf:"varint,8,opt,name=msg_data_id,json=msgDataId,proto3" json:"msg_data_id,omitempty" xml:"MsgDataId"`
	Idx                  int64    `protobuf:"varint,9,opt,name=idx,proto3" json:"idx,omitempty" xml:"Id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveMessageReq) Reset()         { *m = ReceiveMessageReq{} }
func (m *ReceiveMessageReq) String() string { return proto.CompactTextString(m) }
func (*ReceiveMessageReq) ProtoMessage()    {}
func (*ReceiveMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{2}
}
func (m *ReceiveMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveMessageReq.Unmarshal(m, b)
}
func (m *ReceiveMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveMessageReq.Marshal(b, m, deterministic)
}
func (m *ReceiveMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveMessageReq.Merge(m, src)
}
func (m *ReceiveMessageReq) XXX_Size() int {
	return xxx_messageInfo_ReceiveMessageReq.Size(m)
}
func (m *ReceiveMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveMessageReq proto.InternalMessageInfo

func (m *ReceiveMessageReq) GetToUserName() string {
	if m != nil {
		return m.ToUserName
	}
	return ""
}

func (m *ReceiveMessageReq) GetFromUserName() string {
	if m != nil {
		return m.FromUserName
	}
	return ""
}

func (m *ReceiveMessageReq) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ReceiveMessageReq) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *ReceiveMessageReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReceiveMessageReq) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *ReceiveMessageReq) GetMsgDataId() int64 {
	if m != nil {
		return m.MsgDataId
	}
	return 0
}

func (m *ReceiveMessageReq) GetIdx() int64 {
	if m != nil {
		return m.Idx
	}
	return 0
}

// ReceiveMessageRsp 接受普通消息接口回包
type ReceiveMessageRsp struct {
	ToUserName           string   `protobuf:"bytes,1,opt,name=to_user_name,json=toUserName,proto3" json:"to_user_name,omitempty" xml:"ToUserName"`
	FromUserName         string   `protobuf:"bytes,2,opt,name=from_user_name,json=fromUserName,proto3" json:"from_user_name,omitempty" xml:"FromUserName"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" xml:"CreateTime"`
	MsgType              string   `protobuf:"bytes,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty" xml:"MsgType"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty" xml:"Content"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveMessageRsp) Reset()         { *m = ReceiveMessageRsp{} }
func (m *ReceiveMessageRsp) String() string { return proto.CompactTextString(m) }
func (*ReceiveMessageRsp) ProtoMessage()    {}
func (*ReceiveMessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_105fe7df5fe4560f, []int{3}
}
func (m *ReceiveMessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveMessageRsp.Unmarshal(m, b)
}
func (m *ReceiveMessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveMessageRsp.Marshal(b, m, deterministic)
}
func (m *ReceiveMessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveMessageRsp.Merge(m, src)
}
func (m *ReceiveMessageRsp) XXX_Size() int {
	return xxx_messageInfo_ReceiveMessageRsp.Size(m)
}
func (m *ReceiveMessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveMessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveMessageRsp proto.InternalMessageInfo

func (m *ReceiveMessageRsp) GetToUserName() string {
	if m != nil {
		return m.ToUserName
	}
	return ""
}

func (m *ReceiveMessageRsp) GetFromUserName() string {
	if m != nil {
		return m.FromUserName
	}
	return ""
}

func (m *ReceiveMessageRsp) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *ReceiveMessageRsp) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *ReceiveMessageRsp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckSignatureReq)(nil), "woa.CheckSignatureReq")
	proto.RegisterType((*CheckSignatureRsp)(nil), "woa.CheckSignatureRsp")
	proto.RegisterType((*ReceiveMessageReq)(nil), "woa.ReceiveMessageReq")
	proto.RegisterType((*ReceiveMessageRsp)(nil), "woa.ReceiveMessageRsp")
}

func init() { proto.RegisterFile("woa.proto", fileDescriptor_105fe7df5fe4560f) }

var fileDescriptor_105fe7df5fe4560f = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0xe5, 0xe4, 0xd7, 0x26, 0xd9, 0xe6, 0x97, 0x92, 0x25, 0x2a, 0x56, 0x54, 0xea, 0x68,
	0x25, 0x50, 0xc4, 0x9f, 0x58, 0xa2, 0x82, 0x43, 0xc5, 0x29, 0x41, 0x48, 0x1c, 0x8a, 0x90, 0x1b,
	0x2e, 0x5c, 0xac, 0xad, 0x33, 0x75, 0x5c, 0xb2, 0x5e, 0xb3, 0xbb, 0xf9, 0x77, 0x42, 0xe2, 0x15,
	0xb8, 0x20, 0xf1, 0x58, 0xdc, 0xcd, 0x85, 0x27, 0xf0, 0x13, 0xa0, 0x5d, 0xc7, 0x4d, 0xd2, 0xf4,
	0x11, 0x38, 0xe5, 0x3b, 0x33, 0x9f, 0xd9, 0x99, 0xcd, 0x78, 0x16, 0xd5, 0xe6, 0x9c, 0xf6, 0x12,
	0xc1, 0x15, 0xc7, 0xe5, 0x39, 0xa7, 0xed, 0xe3, 0x90, 0xf3, 0x70, 0x02, 0x2e, 0x4d, 0x22, 0x97,
	0xc6, 0x31, 0x57, 0x54, 0x45, 0x3c, 0x96, 0x39, 0xd2, 0x7e, 0x30, 0xa3, 0x93, 0x68, 0x44, 0x15,
	0xb8, 0x85, 0x58, 0x05, 0x5a, 0x21, 0x0f, 0xb9, 0x91, 0xae, 0x56, 0xb9, 0x97, 0x7c, 0x45, 0xcd,
	0xc1, 0x18, 0x82, 0xcf, 0x17, 0x51, 0x18, 0x53, 0x35, 0x15, 0xe0, 0xc1, 0x17, 0x7c, 0x8c, 0x6a,
	0xb2, 0xb0, 0x6d, 0xab, 0x63, 0x75, 0x6b, 0xde, 0xda, 0xa1, 0xa3, 0x2a, 0x62, 0x20, 0x15, 0x65,
	0x89, 0x5d, 0xea, 0x58, 0xdd, 0xb2, 0xb7, 0x76, 0xe0, 0x16, 0xda, 0x8b, 0x79, 0x1c, 0x80, 0x5d,
	0x36, 0x91, 0xdc, 0xc0, 0x36, 0xaa, 0x40, 0x30, 0xe6, 0x52, 0x09, 0xfb, 0x3f, 0x73, 0x5e, 0x61,
	0x92, 0xe7, 0x3b, 0x0d, 0xc8, 0x64, 0x13, 0xb7, 0xb6, 0xf1, 0x1f, 0x65, 0xd4, 0xf4, 0x20, 0x80,
	0x68, 0x06, 0xe7, 0x20, 0x25, 0x0d, 0x4d, 0xc3, 0xaf, 0x50, 0x5d, 0x71, 0x7f, 0x2a, 0x41, 0xf8,
	0x31, 0x65, 0xab, 0x9e, 0xfb, 0xad, 0x2c, 0x75, 0xee, 0x2d, 0xd8, 0xe4, 0x8c, 0x0c, 0xf9, 0x47,
	0x09, 0xe2, 0x3d, 0x65, 0x40, 0x3c, 0xa4, 0x6e, 0x0c, 0xfc, 0x1a, 0x35, 0xae, 0x04, 0x67, 0x1b,
	0x99, 0x25, 0x93, 0x79, 0x94, 0xa5, 0x0e, 0x36, 0x99, 0x6f, 0x05, 0x67, 0xeb, 0xdc, 0xfa, 0xd5,
	0x86, 0x89, 0x5f, 0xa2, 0x83, 0x40, 0x00, 0x55, 0xe0, 0xeb, 0xeb, 0xe7, 0x17, 0xde, 0x28, 0x3a,
	0x30, 0xb1, 0x61, 0x64, 0x8a, 0x06, 0x37, 0x06, 0x7e, 0x86, 0xaa, 0x4c, 0x86, 0xbe, 0x5a, 0x26,
	0x90, 0xff, 0x19, 0xfd, 0x66, 0x96, 0x3a, 0xff, 0x9b, 0x9c, 0x73, 0x19, 0x0e, 0x97, 0x09, 0x10,
	0xaf, 0xc2, 0x72, 0x85, 0x9f, 0xa2, 0x4a, 0xc0, 0x63, 0x05, 0xb1, 0xb2, 0xf7, 0x6f, 0xc1, 0x83,
	0xdc, 0x4f, 0xbc, 0x82, 0xc0, 0x8f, 0xd1, 0xbe, 0x3e, 0x3a, 0x1a, 0xd9, 0x15, 0xd3, 0xcc, 0x61,
	0x96, 0x3a, 0x07, 0xc5, 0xc1, 0xef, 0x46, 0xc4, 0xdb, 0x63, 0xfa, 0x17, 0x9f, 0xa2, 0x03, 0xcd,
	0x8d, 0xa8, 0xa2, 0x1a, 0xae, 0x1a, 0xf8, 0x7e, 0x96, 0x3a, 0x87, 0x05, 0xfc, 0x86, 0x2a, 0xaa,
	0x13, 0x6a, 0xac, 0xd0, 0xf8, 0x04, 0x95, 0xa3, 0xd1, 0xc2, 0xae, 0x19, 0xb8, 0x9e, 0xa5, 0x4e,
	0xd5, 0xc0, 0x9a, 0xd2, 0x01, 0xf2, 0xb3, 0xb4, 0x33, 0x1a, 0x99, 0xfc, 0x1b, 0x4d, 0xae, 0x5e,
	0xfc, 0xb6, 0x50, 0xf5, 0x83, 0xe0, 0x8b, 0xe5, 0xc5, 0x4c, 0xe0, 0x10, 0x35, 0xb6, 0x3f, 0x7a,
	0x7c, 0xd4, 0xd3, 0x5b, 0xbe, 0xb3, 0x8a, 0xed, 0x3b, 0xfd, 0x32, 0x21, 0x8f, 0xbe, 0xfd, 0xfa,
	0xf3, 0xbd, 0xe4, 0xe0, 0x87, 0xee, 0xea, 0x75, 0x58, 0x2c, 0xe5, 0x4c, 0xb8, 0x81, 0x06, 0xfd,
	0xf5, 0xae, 0x5e, 0xa3, 0xc6, 0xf6, 0x48, 0x56, 0x85, 0x76, 0x56, 0xa8, 0x7d, 0xa7, 0x5f, 0x26,
	0xa4, 0x6b, 0x0a, 0x11, 0x72, 0xab, 0x90, 0xc8, 0x41, 0x9f, 0xe5, 0xe4, 0x99, 0xf5, 0xa4, 0xdf,
	0xf9, 0x74, 0x12, 0x46, 0x6a, 0x3c, 0xbd, 0xec, 0x05, 0x9c, 0xb9, 0xd7, 0x10, 0x4b, 0x88, 0xc3,
	0x29, 0x77, 0xf3, 0x37, 0x67, 0xce, 0xe9, 0xe5, 0xbe, 0x91, 0xa7, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x5a, 0xcb, 0xcd, 0xd8, 0xd2, 0x04, 0x00, 0x00,
}
