// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.5.0
// source: woa.proto

package woa

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProxySvrCheckSignature = "/woa.ProxySvr/CheckSignature"
const OperationProxySvrReceiveMessage = "/woa.ProxySvr/ReceiveMessage"

type ProxySvrHTTPServer interface {
	// CheckSignature CheckSignature 签名校验接口
	CheckSignature(context.Context, *CheckSignatureReq) (*CheckSignatureRsp, error)
	// ReceiveMessage ReceiveMessage 接受普通消息接口
	ReceiveMessage(context.Context, *ReceiveMessageReq) (*ReceiveMessageRsp, error)
}

func RegisterProxySvrHTTPServer(s *http.Server, srv ProxySvrHTTPServer) {
	r := s.Route("/")
	r.GET("/woa.proxysvr/check_signature", _ProxySvr_CheckSignature0_HTTP_Handler(srv))
	r.POST("/woa.proxysvr/receive_message", _ProxySvr_ReceiveMessage0_HTTP_Handler(srv))
}

func _ProxySvr_CheckSignature0_HTTP_Handler(srv ProxySvrHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckSignatureReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProxySvrCheckSignature)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckSignature(ctx, req.(*CheckSignatureReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckSignatureRsp)
		return ctx.String(200, reply.Echostr)
	}
}

func _ProxySvr_ReceiveMessage0_HTTP_Handler(srv ProxySvrHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReceiveMessageReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProxySvrReceiveMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReceiveMessage(ctx, req.(*ReceiveMessageReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReceiveMessageRsp)
		return ctx.Result(200, reply)
	}
}

type ProxySvrHTTPClient interface {
	CheckSignature(ctx context.Context, req *CheckSignatureReq, opts ...http.CallOption) (rsp *CheckSignatureRsp, err error)
	ReceiveMessage(ctx context.Context, req *ReceiveMessageReq, opts ...http.CallOption) (rsp *ReceiveMessageRsp, err error)
}

type ProxySvrHTTPClientImpl struct {
	cc *http.Client
}

func NewProxySvrHTTPClient(client *http.Client) ProxySvrHTTPClient {
	return &ProxySvrHTTPClientImpl{client}
}

func (c *ProxySvrHTTPClientImpl) CheckSignature(ctx context.Context, in *CheckSignatureReq, opts ...http.CallOption) (*CheckSignatureRsp, error) {
	var out CheckSignatureRsp
	pattern := "/woa.proxysvr/check_signature"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProxySvrCheckSignature))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out.Echostr, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ProxySvrHTTPClientImpl) ReceiveMessage(ctx context.Context, in *ReceiveMessageReq, opts ...http.CallOption) (*ReceiveMessageRsp, error) {
	var out ReceiveMessageRsp
	pattern := "/woa.proxysvr/receive_message"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProxySvrReceiveMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
